export const MembershipConfigConstants = {

  ASSET_TYPES: "/menu/configurations/membership_config/asset_types",
  ADD_ASSET_TYPE: "/menu/configurations/membership_config/add_asset_type",
  COMMON_CATEGORY: "/menu/configurations/membership_config/common_category",
  ADD_COMMON_CATEGORY: "/menu/configurations/membership_config/add_common_category",
  FEE_TYPES: "/menu/configurations/membership_config/fee_types",
  ADD_FEE_TYPE: "/menu/configurations/membership_config/add_fee_type",
  GROUP_TYPES: "/menu/configurations/membership_config/group_types",
  ADD_GROUP_TYPE: "/menu/configurations/membership_config/add_group_type",
  INCORPORATION_TYPES: "/menu/configurations/membership_config/incorporation_types",
  ADD_INCORPORATION_TYPE: "/menu/configurations/membership_config/add_incorporation_type",
  IRRIGATION_TYPES: "/menu/configurations/membership_config/irrigation_types",
  ADD_IRRIGATION_TYPE: "/menu/configurations/membership_config/add_irrigation_type",
  MCR_DETAILS: "/menu/configurations/membership_config/mcr_details",
  ADD_MCR_DETAILS: "/menu/configurations/membership_config/add_mcr_details",
  SEASON_TYPES: "/menu/configurations/membership_config/season_types",
  ADD_SEASON_TYPE: "/menu/configurations/membership_config/add_season_type",
  SETTINGS: "/menu/configurations/membership_config/settings",
  ADD_SETTING: "/menu/configurations/membership_config/add_setting",
  SOIL_TYPES: "/menu/configurations/membership_config/soil_types",
  ADD_SOIL_TYPE: "/menu/configurations/membership_config/add_soil_type",
  UOM: "/menu/configurations/membership_config/uom",
  ADD_UOM: "/menu/configurations/membership_config/add_uom",
  UOM_CALCULATIONS: "/menu/configurations/membership_config/uom_calculations",
  ADD_UOM_CALCULATION: "/menu/configurations/membership_config/add_uom_calculation",
  WATER_SOURCE_TYPES: "/menu/configurations/membership_config/water_source_types",
  ADD_WATER_SOURCE_TYPE: "/menu/configurations/membership_config/add_water_source_type",
  WORK_FLOW: "/menu/configurations/membership_config/workflow",
  ADD_WORK_FLOW: "/menu/configurations/membership_config/add_workflow",
  DOCUMENT_TYPES: "/menu/configurations/membership_config/document_types",
  ADD_DOCUMENT_TYPE: "/menu/configurations/membership_config/add_document_type",
  VOTER_CONFIG: "/menu/configurations/membership_config/voter_config",
  ADD_VOTER_CONFIG: "/menu/configurations/membership_config/add_voter_config",
  PRODUCTS: "/menu/configurations/membership_config/products",
  ADD_PRODUCTS: "/menu/configurations/membership_config/add_products",
  LAND_TYPES: "/menu/configurations/membership_config/land_types",
  ADD_LAND_TYPES: "/menu/configurations/membership_config/add_land_types",
  LAND_OWNERSHIP_TYPES: "/menu/configurations/membership_config/land_ownership_types",
  ADD_LAND_OWNERSHIP_TYPES: "/menu/configurations/membership_config/add_land_ownership_types",
}

