
export const CommonConfigConstants = {
 
   ACCOUNT_TYPES:"/menu/configurations/common_config/account_types",
   ADD_ACCOUNT_TYPE:"/menu/configurations/common_config/add_account_type",
   BLOCK:"/menu/configurations/common_config/block",
   ADD_BLOCK:"/menu/configurations/common_config/add_block",
   CASTE:"/menu/configurations/common_config/caste",
   ADD_CASTE:"/menu/configurations/common_config/add_caste",
   COMMUNITY:"/menu/configurations/common_config/community",
   ADD_COMMUNITY:"/menu/configurations/common_config/add_community",
   DISTRICT:"/menu/configurations/common_config/district",
   ADD_DISTRICT:"/menu/configurations/common_config/add_district", 
   DIVISION:"/menu/configurations/common_config/division",
   ADD_DIVISION:"/menu/configurations/common_config/add_division", 
   INTEREST_POSTING_FREQUENCY : "/menu/configurations/common_config/interest_posting_frequency",
   ADD_INTEREST_POSTING_FREQUENCY : "/menu/configurations/common_config/add_interest_posting_frequency",
   OCCUPATIOON_TYPES: "/menu/configurations/common_config/occupation_types",
   ADD_OCCUPATIOON_TYPE : "/menu/configurations/common_config/add_occupation_type",
   QUALIFICATION: "/menu/configurations/common_config/qualification",
   ADD_QUALIFICATION :"/menu/configurations/common_config/add_qualification",
   RELATION_TYPES:"/menu/configurations/common_config/relation_types",
   ADD_RELATION_TYPE:"/menu/configurations/common_config/add_relation_type",
   STATE:"/menu/configurations/common_config/state",
   ADD_STATE:"/menu/configurations/common_config/add_state",
   SUB_DISTRICT:"/menu/configurations/common_config/sub_district",
   ADD_SUB_DISTRICT:"/menu/configurations/common_config/add_sub_district",
   TRANSCATION_MODE:"/menu/configurations/common_config/transaction_mode",
   ADD_TRANSCATION_MODE:"/menu/configurations/common_config/add_transaction_mode",
   VILLAGES:"/menu/configurations/common_config/villages",
   ADD_VILLAGES:"/menu/configurations/common_config/add_villages",
   ADD_SETTINGS:"/menu/configurations/term_deposit_config/add_villages",
   DCCB:"/menu/configurations/common_config/dccb",
   ADD_DCCB:"/menu/configurations/common_config/add_dccb",
   DCCB_BRANCH:"/menu/configurations/common_config/dccb_branch",
   ADD_DCCB_BRANCH:"/menu/configurations/common_config/add_dccb_branch",
   DENOMINATION_TYPES:"/menu/configurations/common_config/denomination_types",
   ADD_DENOMINATION_TYPE:"/menu/configurations/common_config/add_denomination_type",
   MEMBER_TYPES:"/menu/configurations/common_config/member_types",
   ADD_MEMBER_TYPE:"/menu/configurations/common_config/add_member_type",
   COVERED_VILLAGES:"/menu/configurations/common_config/covered_villages",
   ADD_COVERED_VILLAGES:"/menu/configurations/common_config/add_covered_villages",
   SOCIETY:"/menu/configurations/common_config/society",
   ADD_SOCIETY:"/menu/configurations/common_config/add_society",
   SOCIETY_BRANCH:"/menu/configurations/common_config/society_branch",
   ADD_SOCIETY_BRANCH:"/menu/configurations/common_config/add_society_branch",
   OPERATOR_TYPES:"/menu/configurations/common_config/operator_types",
   ADD_OPERATOR_TYPE:"/menu/configurations/common_config/add_operator_type",
   DESIGNATION_TYPES:"/menu/configurations/common_config/designation_types",
   ADD_DESIGNATION_TYPE:"/menu/configurations/common_config/add_designation_type",
   KYC_DOCUMENT_TYPES:"/menu/configurations/common_config/kyc_document_types",
   ADD_KYC_DOCUMENT_TYPE:"/menu/configurations/common_config/add_kyc_document_type",
}  
