export class AgentDetails {
    id: any;
    agentId: any;
    pacsId: any;
    pacsCode: any;
    branchId: any;
    admissionNumber: any;
    tempAdmissionNumber: any;
    agentType: any;
    taskType: any;
    surName: any;
    name: any;
    nameInLocalLanguage: any;
    singatureCopyPath: any;
    photoCopyPath: any;
    genderId: any;
    martialId: any;
    maritalStatusName: any;
    relationId: any;
    relativeName: any;
    community: any;
    casteId: any;
    qualificationId: any;
    occupationId: any;
    incomePerAnnum: any;
    status: any;
    effectiveStartDate: any;
    effectiveEndDate: any;
    statusName: any;
    remarks: any;
    commissionPaymentFrequency: any;
    totalEnrollments: any;
    totalCollectionAmount: any;
    currentEnrollments: any;
    currentCollectionAmount: any;
    agentTotalCommisionAmount: any;
    lastCommissionPaymentDate: any;
    lastCommissionPaymentAmount: any;
    penaltyAmount: any;
    accountNumber: any;
    ifscCode: any;
    memberShipBasicDetailsDTO:any;
    agentCommunicationList:any;
    agentNomineeList:any;
    agentKycDetailsList:any;
    agentSecurityList:any;
    agentSurityDetailsList:any;
    collectionType:any;
    dob:any;
    age:any;
    aadharNumber:any;
    panNumber:any;
    mobileNumber:any;
    emailId:any;
    admissionDate:any;
    genderName:any;
    relationTypeName:any;
    casteName: any;
    agentTypeName:any;
    taskTypeName:any;
    collectionTypeName:any;
}


