
export const Loantransactionconstant = {
    LOANS_TRANSACTION:"/menu/loan_transaction/loan_transactions",
    COMPOUND_INTEREST_LOAN:"/menu/loan_transaction/compound_interest_loans",
    DEPOSITOR_LOAN:"/menu/loan_transaction/depositor_loans",
    SIMPLE_INTEREST_LOANS_TRANSACTION:"/menu/loan_transaction/simple_interest_loans",
    SAO_LOAN:"/menu/loan_transaction/sao_loans",
    TERM_LOAN:"/menu/loan_transaction/term_loans",

    LOANS_SAO_STEPPER :"/menu/loan_transaction/sao_stepper",
    LOANS_TERM_LOANS_STEPPER:"/menu/loan_transaction/term_loans_stepper",
    SIMPLE_INTEREST_LOANS_STEPPER:"/menu/loan_transaction/simple_interest_loans_stepper",
    LOANS_COMPOUND_INTEREST_LOANS_STEPPER:"/menu/loan_transaction/compound_interest_loans_stepper",
    LOANS_DEPOSITOR_LOANS_STEPPER:"/menu/loan_transaction/depositor_loans_stepper",
    
    LOANS_DISBURSEMENT :"/menu/loan_transaction/disbursement",
    LOANS_COLLECTIONS:"/menu/loan_transaction/collections",
    LOANS_CLOSURE:"/menu/loan_transaction/closure",
    VIEW_LOANS:"/menu/loan_transaction/view_loans",
    EDIT_LOANS:"/menu/loan_transaction/edit_loans",

    MEMBERSHIP_BASIC_DETAILS:"/menu/loan_transaction/sao_stepper/membership_basic_details",
    SAO_PRODUCT_DETAILS:"/menu/loan_transaction/sao_stepper/sao_product_details",
    SAO_LOAN_JOINT_MEM_DETAILS:"/menu/loan_transaction/sao_stepper/sao_loan_joint_member_details",
    SAO_COMMUNICATION:"/menu/loan_transaction/sao_stepper/sao_communication",
    SAO_KYC:"/menu/loan_transaction/sao_stepper/sao_kyc",
    SAO_LOAN_GUARANTOR:"/menu/loan_transaction/sao_stepper/sao_loan_guarantor",
    SAO_NOMINEE:"/menu/loan_transaction/sao_stepper/sao_nominee",
    SAO_LOAN_MORTAGAGE :"/menu/loan_transaction/sao_stepper/sao_loan_mortagage",
    SAO_LOAN_DOCUMENTS:"/menu/loan_transaction/sao_stepper/sao_loan_documents",
    SAO_LOAN_GENEALOGY_TREE:"/menu/loan_transaction/sao_stepper/sao_loan_genealogy_tree",

    VIEW_SAO_LOANS:"/menu/loan_transaction/view_sao_loans",
    SAO_LOAN_DISBURSMENT:"/menu/loan_transaction/sao_loan_disbursment",
    SAO_LOAN_COLLECTIONS:"/menu/loan_transaction/sao_loan_collections",
    SAO_CLOSURE:"/menu/loan_transaction/sao_closure",

    SIMPLE_INTEREST_LOANS_MEMBERSHIP_DETAILS :"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_membership_details",
    SIMPLE_INTEREST_LOANS_NEW_MEMBERSHIP_DETAILS :"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_new_membership_details",
    SIMPLE_INTEREST_LOANS_KYC:"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_kyc",
    SIMPLE_INTEREST_LOANS_COMMUNICATION:"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_communication",
    SIMPLE_INTEREST_LOANS_APPLICATION_DETAILS :"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_application_details",
    SIMPLE_INTEREST_LOANS_JOINT_ACCOUNT :"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_joint_account_details",
    SIMPLE_INTEREST_LOANS_NOMINEE :"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_nominee",
    SIMPLE_INTEREST_LOANS_GUARANTOR :"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_guarantor",
    SIMPLE_INTEREST_LOANS_MORTAGAGE:"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_mortagage",
    SIMPLE_INTEREST_LOANS_DOCUMENTS:"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_documents",
    SIMPLE_INTEREST_LOANS_GENEALOGY_TREE:"/menu/loan_transaction/simple_interest_loans_stepper/simple_interest_loans_genealogy_tree",

    PREVIEW_TERM_LOAN:"/menu/loan_transaction/preview_term_loan",
    TERMLOANS_PRODUCT_DETAILS:"/menu/loan_transaction/term_loans_stepper/term_loans_product_details",
    TERMLOANS_COMMUNICATION:"/menu/loan_transaction/term_loans_stepper/term_loans_communication",
    TERMLOANS_KYC:"/menu/loan_transaction/term_loans_stepper/term_loans_kyc",
    TERMLOANS_GUARANTOR:"/menu/loan_transaction/term_loans_stepper/term_loans_guarantor",
    TERMLOANS_NOMINEE:"/menu/loan_transaction/term_loans_stepper/term_loans_nominee",
    TERMLOANS_MORTAGAGE:"/menu/loan_transaction/term_loans_stepper/term_loans_mortagage",
    TERM_LOAN_DOCUMENTS:"/menu/loan_transaction/term_loans_stepper/term_loans_documents",
    TERMLOANS_GENEALOGY_TREE:"/menu/loan_transaction/term_loans_stepper/term_loans_genealogy_tree",
    TERMLOANS_APPLICATION_DETAILS:"/menu/loan_transaction/term_loans_stepper/term_loans_application_details",
    TERMLOANS_JOINT_ACCOUNT:"/menu/loan_transaction/term_loans_stepper/term_loans_joint_account",
    TERMLOANS_NEW_MEMBERSHIP:"/menu/loan_transaction/term_loans_stepper/term_loans_new_membership",
    TERMLOANS_MEMBERSHIP:"/menu/loan_transaction/term_loans_stepper/term_loans_membership",


    COMPOUND_INTEREST_LOANS_MEMBERSHIP_DETAILS:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_membership_details",
    COMPOUND_INTEREST_LOANS_APPLICATIOIN_DETAILS:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_product_details",
    COMPOUND_INTEREST_LOANS_COMMUNICATON:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_communication",
    COMPOUND_INTEREST_LOANS_KYC:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_kyc",
    COMPOUND_INTEREST_LOANS_GUARANTOR:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_guarantor",
    COMPOUND_INTEREST_LOANS_NOMINEE:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_nominee",
    COMPOUND_INTEREST_LOANS_MORTAGAGE:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_mortagage",
    COMPOUND_INTEREST_LOANS_DOCUMENTS:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_documents",
    COMPOUND_INTEREST_LOANS_GENEALOGY_TREE:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_genealogy_tree",
    COMPOUND_INTEREST_LOANS_CO_APPLICANT_DETAILS:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_co_applicant_details",
    COMPOUND_INTEREST_LOANS_NEW_MEMBERSHIP_DETAILS:"/menu/loan_transaction/compound_interest_loans_stepper/compound_interest_loans_new_membership_details",
    COMPOUND_INTEREST_LOANS_PREVIEW:"/menu/loan_transaction/compound_interest_loans_preview",
    COMPOUND_INTEREST_APPROVAL : "/menu/approval_transactions/ci_loan_approval_grid",
    COMPOUND_INTEREST_APPROVAL_STATUS_UPDATE :"/menu/approval_transactions/ci_loan_approval_status_update",
    COMPOUND_INTEREST_GUARENTOR_DETAILS_APPLICATION_ID : "/get_loan_application_id",

    DEPOSITOR_LOANS_PRODUCT_DETAILS:"/menu/loan_transaction/depositor_loans_stepper/depositor_loans_product_details",
    DEPOSITOR_LOANS_COMMUNICATON:"/menu/loan_transaction/depositor_loans_stepper/depositor_loans_communication",
    DEPOSITOR_LOANS_NOMINEE:"/menu/loan_transaction/depositor_loans_stepper/depositor_loans_nominee",
    DEPOSITOR_LOANS_MORTAGAGE:"/menu/loan_transaction/depositor_loans_stepper/depositor_loans_mortagage",
    DEPOSITOR_LOANS_DOCUMENTS:"/menu/loan_transaction/depositor_loans_stepper/depositor_loans_documents",

    SAO_PRODUCT_DEFINITION:"/menu/loan_transaction/sao_loan_product_definition",
    SAO_PRODUCT_DEFINITION_STEPPER:"/menu/loan_transaction/sao_loan_product_definition_stepper",
    SAO_PRODUCT_CONFIGURATION:"/menu/loan_transaction/sao_loan_product_definition_stepper/sao_product_configuration",
    SAO_INTEREST_POLICY_CONFIG:"/menu/loan_transaction/sao_loan_product_definition_stepper/sao_interest_policy_config",
    SAO_LOAN_LINKED_SHARE_CAPITAL:"/menu/loan_transaction/sao_loan_product_definition_stepper/sao_loan_linked_share_capital",
    SAO_PRODUCT_CHARGES_CONFIG:"/menu/loan_transaction/sao_loan_product_definition_stepper/sao_product_charges_config",
    SAO_PROD_PURPOSE_CONFIG:"/menu/loan_transaction/sao_loan_product_definition_stepper/sao_prod_purpose_config",
    SAO_REQUIRED_DOCUMENT_CONFIG:"/menu/loan_transaction/sao_loan_product_definition_stepper/sao_required_documents_config",
    VIEW_SAO_PRODUCT_DEFINITION:"/menu/loan_transaction/view_sao_loan_product_definition",

    VIEW_SIMPLE_INTEREST_LOAN:"/menu/loan_transaction/view_simple_interest_loan",
    SIMPLE_INTEREST_LOAN_DISBURSEMENTS :"/menu/loan_transaction/simple_interest_loan_disbursement",
    SIMPLE_INTEREST_LOAN_COLLECTIONS:"/menu/loan_transaction/simple_interest_loan_collections",
    SIMPLE_INTEREST_LOAN_CLOSURE:"/menu/loan_transaction/simple_interest_loan_closure",

    SIMPLE_INTEREST_PRODUCT_DEFINITION:"/menu/loan_transaction/simple_interest_loan_product_definition",
    SIMPLE_INTEREST_PRODUCT_DEFINITION_STEPPER:"/menu/loan_transaction/simple_interest_loan_product_definition_stepper",
    SIMPLE_INTEREST_PRODUCT_CONFIGURATION:"/menu/loan_transaction/simple_interest_loan_product_definition_stepper/simple_interest_product_configuration",
    SIMPLE_INTEREST_INTEREST_POLICY_CONFIG:"/menu/loan_transaction/simple_interest_loan_product_definition_stepper/simple_interest_interest_policy_config",
    SIMPLE_INTEREST_LOAN_LINKED_SHARE_CAPITAL:"/menu/loan_transaction/simple_interest_loan_product_definition_stepper/simple_interest_loan_linked_share_capital",
    SIMPLE_INTEREST_PRODUCT_CHARGES_CONFIG:"/menu/loan_transaction/simple_interest_loan_product_definition_stepper/simple_interest_product_charges_config",
    SIMPLE_INTEREST_PROD_PURPOSE_CONFIG:"/menu/loan_transaction/simple_interest_loan_product_definition_stepper/simple_interest_prod_purpose_config",
    SIMPLE_INTEREST_REQUIRED_DOCUMENT_CONFIG:"/menu/loan_transaction/simple_interest_loan_product_definition_stepper/simple_interest_required_documents_config",
    VIEW_SIMPLE_INTEREST_PRODUCT_DEFINITION:"/menu/loan_transaction/view_simple_interest_loan_product_definition",


    COMPOUND_INTEREST_PRODUCT_DEFINITION:"/menu/loan_transaction/compound_interest_loan_product_definition",
    COMPOUND_INTEREST_PRODUCT_DEFINITION_STEPPER:"/menu/loan_transaction/compound_interest_loan_product_definition_stepper",
    COMPOUND_INTEREST_PRODUCT_CONFIGURATION:"/menu/loan_transaction/compound_interest_loan_product_definition_stepper/compound_interest_product_configuration",
    COMPOUND_INTEREST_INTEREST_POLICY_CONFIG:"/menu/loan_transaction/compound_interest_loan_product_definition_stepper/compound_interest_interest_policy_config",
    COMPOUND_INTEREST_LOAN_LINKED_SHARE_CAPITAL:"/menu/loan_transaction/compound_interest_loan_product_definition_stepper/compound_interest_loan_linked_share_capital",
    COMPOUND_INTEREST_PRODUCT_CHARGES_CONFIG:"/menu/loan_transaction/compound_interest_loan_product_definition_stepper/compound_interest_product_charges_config",
    COMPOUND_INTEREST_PROD_PURPOSE_CONFIG:"/menu/loan_transaction/compound_interest_loan_product_definition_stepper/compound_interest_prod_purpose_config",
    COMPOUND_INTEREST_REQUIRED_DOCUMENT_CONFIG:"/menu/loan_transaction/compound_interest_loan_product_definition_stepper/compound_interest_required_documents_config",
    VIEW_COMPOUND_INTEREST_PRODUCT_DEFINITION:"/menu/loan_transaction/view_compound_interest_loan_product_definition",

    TERM_LOAN_PRODUCT_DEFINITION:"/menu/loan_transaction/term_loan_product_definition",
    TERM_LOAN_PRODUCT_DEFINITION_STEPPER:"/menu/loan_transaction/term_loan_product_definition_stepper",
    TERM_LOAN_PRODUCT_CONFIGURATION:"/menu/loan_transaction/term_loan_product_definition_stepper/term_loan_product_configuration",
    TERM_LOAN_INTEREST_POLICY_CONFIG:"/menu/loan_transaction/term_loan_product_definition_stepper/term_loan_interest_policy_config",
    TERM_LOAN_LOAN_LINKED_SHARE_CAPITAL:"/menu/loan_transaction/term_loan_product_definition_stepper/term_loan_loan_linked_share_capital",
    TERM_LOAN_PRODUCT_CHARGES_CONFIG:"/menu/loan_transaction/term_loan_product_definition_stepper/term_loan_product_charges_config",
    TERM_LOAN_PROD_PURPOSE_CONFIG:"/menu/loan_transaction/term_loan_product_definition_stepper/term_loan_prod_purpose_config",
    TERM_LOAN_REQUIRED_DOCUMENT_CONFIG:"/menu/loan_transaction/term_loan_product_definition_stepper/term_loan_required_documents_config",
    VIEW_TERM_LOAN_PRODUCT_DEFINITION:"/menu/loan_transaction/view_term_loan_product_definition",
}

