import { environment } from "src/environments/environment";
// import { CoveredVillages } from "../configurations/membership-config/membership-covered-villages/shared/covered-villages.model";
import { CropTypes } from "../configurations/loan-config/crop-types/shared/crop-types.model";
import { UpdateModeEnum } from "chart.js";

export const ERP_TRANSACTION_CONSTANTS = {

    COMMON_MASTER: environment.commonmaster,
    MEMBERSHIP: environment.membership,
    DEMANDDEPOSITS: environment.demanddeposits,
    TERMDEPOSITS: environment.termdeposits,
    LOANS: environment.loans,
    DAILYDEPOSITS: environment.dailydeposits,
    BORROWINGS: environment.borrowings,
    CASHCOUNTER: environment.cashcounter,
    AGENTDETAILS: environment.agentmanagement,
    RBAC: environment.rbac,
    LOCKERS:environment.lockers,
    INVESTMENTS:environment.investments,
    
    ADD: '/add',
    UPDATE: '/update',
    GET: '/get',
    GET_ALL: '/get_all',
    GET_ALL_GRID: '/get_all_grid',
    DELETE: '/remove',
    ADD_ALL: '/add_all',
    BLOCKS:'/blocks',
    DIVISION:'/division',
    TRANSFER_TRANSACTION_DETAILS: '/transfer_transaction_details',
    STANDING_INSTRUCTIONS_PAYMENTS: '/standing_instructions_payments',
    SB_TRANSACTION_DETAILS: '/sb_transaction_details',
    APPROVE_SB_TRANSACTION: '/approve_sb_transaction',
    SB_STANDING_INSTRUCTIONS: '/sb_standing_instructions',
    GET_ALL_BY_ACCOUNT_NUMBER: '/get_all_by_account_number',
    SB_NOMINEE: '/sb_nominee',
    GET_NOMINEE_DETAILS_BY_ACCOUNT_NUMBER: '/get_nominee_details_by_account_number',
    SB_JOINT_ACC_HOLDER_DETAILS: '/sb_joint_acc_holder_details',
    SB_GUARDIAN_DETAILS: '/sb_guardian_details',
    GET_GUARDIAN_DETAILS_BY_ACCOUNT_NUMBER: 'get_guardian_details_by_account_number',
    SB_FORM_TYPES: '/sb_form_types',
    SB_COMMUNICATIONS: '/sb_communications',
    GET_COMMUNICATION_DETAILS_BY_SB_ACCOUNT_ID_AND_COMMUNICATIONTYPE: '/get_communication_details_by_sb_account_id_and_communicationType',
    GET_COMMUNICATION_BY_ACCOUNT_ID_AND_MEMBER_TYPE_AND_MEMBER_ID: '/get_communcation_by_accountId_and_member_type_and_member_id',
    GET_COMMUNICATION_BY_ACCOUNT_ID_AND_MEMBER_TYPE_AND_ADMISSION_NUMBER: '/get_communcation_by_accountId_and_member_type_and_admission_number',
    GET_BY_SB_ACC_ID_OR_JOINT_HOLDER_ID: '/get_by_sb_acc_id_or_joint_holder_id',
    SB_CASH_TRANSACTION_DENOMINATION: '/sb_cash_transaction_denominations',
    SB_AMOUNT_BLOCKING_DETAILS: '/sb_amount_blocking_details',
    SB_BLOCKED_AMOUNT_APPROVAL: '/sb_blocked_amount_approval',
    GET_ALL_BLOCKED_AMOUNTS_BY_ACCOUNT_NUMBER: '/get_all_blocked_amounts_by_account_number',
    SB_ACCOUNT_SERVICES_OPTED: '/sb_account_services_opted',
    GET_ACCOUNT_SERVICES_BY_SB_ACC_ID: '/get_account_services_by_sb_acc_id',
    SB_ACCOUNT_SERVICE_PAYMENTS: '/sb_account_service_payments',
    SB_ACC_KYC_DETAILS: '/sb_acc_kyc_details',
    GET_KYC_DETAILS_BY_SB_ACC_ID: '/get_kyc_details_by_sb_acc_id',
    GET_KYC_BY_ACC_ID_AND_MEMBER_TYPE_AND_MEMBER_ID: '/get_Kyc_by_acc_id_and_member_type_and_member_id',
    GET_KYC_BY_ACC_ID_AND_MEMBER_TYPE_AND_ADMISSION_NUMBER: '/get_Kyc_by_acc_id_and_member_type_and_admission_number',
    SAVINGS_ACCOUNT: '/savings_account',
    GET_SAVINGS_ACCOUNT_DETAILS_BY_PACS_ID_AND_BRANCH_ID: '/get_savings_account_details_by_pacs_id_and_branch_id',
    GET_SAVING_ACCOUNT_BY_ADMISSION_NUMBER_AND_ID: '/get_saving_account_by_admission_number_and_id',
    PRODUCT_DEFINITION: '/product_definition',
    PACS_DETAILS: '/pacs_details',
    MEMBERSHIP_GROUP_DETAILS: '/membership_group_details',
    MEMBERSHIP_BASIC_DETAILS: '/membership_basic_details',
    INDIVIDUAL_MEMBER_DETAILS:'/individual_member_details',
    MEM_INSTITUTIONS: '/mem_institutions',
    ISSUED_CHEQUE_BOOK_DETAILS: '/issued_cheque_book_details',
    GET_ISSUED_CHEQUE_BOOK_BY_ACCOUNT_NUMBER: '/get_issued_cheque_book_by_account_number',
    INTEREST_POSTING_DETAILS: '/interest_posting_details',
    INSTITUTION_PROMOTER_DETAILS: '/institution_promoter_details',
    GET_INSTITUTION_PROMOTER_DETAILS_BY_INSTITUTION_ID_AND_PACSID: '/get_insititution_promoter_details_by_institutionId_and_pacsId',
    TRANSACTION_LIMIT_CONFIG: '/transaction_limit_config',
    GET_TRANSACTION_LIMIT_CONFIG_BY_PRODUCT_ID: '/get_transaction_limit_config_by_product_id',
    REQUIRED_DOCUMENT_CONFIG: '/required_documents_config',
    GET_REQUIRED_DOCUMENTS_CONFIG_BY_PRODUCT_ID: '/get_requried_documents_config_by_product_id',
    INTEREST_POLICY_CONFIG: '/interest_policy_config',
    GET_SB_ROI: '/get_sb_roi',
    GET_INTEREST_POLICY_CONFIG_BY_PRODUCT_ID: '/get_interst_policy_config_by_product_id',
    GROUP_PROMOTERS: '/group_promoters',
    GET_GROUP_PROMOTERS_DETAILS_BY_GROUP_ID: '/get_group_promoter_details_by_group_id',
    CHEQUE_TRANSACTION_DETAILS: '/cheque_transaction_details',
    CHEQUE_BOOK_LEAFS_DETAILS: '/cheque_book_leafs_details',
    AUTO_PAYMENTS_SUMMARIES: '/auto_payments_summaries',
    GET_AUTO_PAYMENT_SUMMARY_BY_AUTO_PAYMENT_LIST: '/get_auto_payment_summary_by_autopayment_list',
    AUTO_PAYMENTS_DETAILS: '/auto_payments_details',
    ACCOUNT_SERVICE_CONFIG_CHARGES: '/account_service_config_charges',
    GET_ACCOUNT_SERVICE_CONFIG_CHARGES_BY_PRODUCT_ID: '/get_account_service_config_Charges_by_product_id',
    MEMBERSHIP_FAMILY_DETAILS: '/membeship_family_details',
    MEMBERSHIP_NOMINEE_DETAILS: '/membership_nominee_details',
    MEMBERSHIP_LAND_DETAILS: '/membership_land_details',
    MEMBERSHIP_KYC_DETAILS: '/membership_kyc_details',
    MEMBERSHIP_FEE_DETAILS: '/membership_fee_details',
    MEMBERSHIP_COMMUNICATION: '/membership_communication',
    MEMBERSHIP_BANK_DETAILS: '/member_bank_details',
    GET_MEMBER_NOMINEE_DETAILS_BY_MEMBERSHIP_ID_AND_PACS_ID: '/get_member_nominee_details_by_membershipId_and_pacsId',
    GET_MEMBER_LAND_DETAILS_BY_MEMBERSHIP_ID_AND_PACS_ID: '/get_member_land_details_by_memberId_and_pacsId',
    GET_MEMBER_KYC_DETAILS_BY_MEMBERSHIP_ID_AND_PACS_ID: '/get_kyc_details_by_memberId_and_pacsId_and_branchId',
    GET_ALL_DETAILS_BY_MEMBERSHIP_ID: '/get_all_details_by_member_id',
    GET_MEMBER_FEE_DETAILS_BY_MEMBERSHIP_ID_AND_PACS_ID: '/get_member_fee_details_by_memberId_and_pacsId',
    GET_MEMBER_COMMUNICATION_DETAILS_BY_MEMBERSHIP_ID_AND_PACS_ID: '/get_member_communication_details_by_memberId_and_pacsId',
    GET_MEMBER_GUARDIAN_DETAILS_BY_MEMBERSHIP_ID_AND_PACSID: '/get_member_guardian_details_by_membershipId_and_pacsId',
    MEMBER_GUARDIAN_DETAILS: '/member_guardian_details',
    GET_INSTITUTION_KYC_DETAILS_BY_INSTITUTE_ID_AND_PACSID: "/get_insititution_kyc_details_by_instituteId_and_pacsId",
    INSTITUTION_KYC_DETAILS: '/institution_kyc_details',
    GET_MEMBERSHIP_BASIC_DETAILS: '/get_membership_details_by_id',
    MEMBERSHIP_ASSETS_DETAILS: '/membership_assets_details',
    GET_MEMBER_ASSETS_DETAILS_BY_MEMBER_ID_AND_PACS_ID_BRANCH_ID: '/get_member_assets_details_by_memberId_and_pacsId_branchId',
    GET_MEMBER_NOMINEE_GUARDIAN_DETAILS_BY_MEMBERSHIP_ID_AND_PACS_ID: '/get_member_nominee_guardian_details_by_membershipId_and_pacsId',
    MEMBER_NOMINEE_GUARDIAN_DETAILS: '/member_nominee_guardian_details',
    MEMBER_LAND_LOAN_MAPPING: '/member_land_loan_mappings',
    MEMBER_LAND_FILE_DETAILS: '/member_land_file_details',
    MEMBER_FILE_DETAILS: '/member_file_details',
    GET_MEMBER_FILE_DETAILS_BY_MEMBER_ID: '/get_member_file_details_by_memberId',
    GET_KYC_DETAILS_BY_ADMISSION_NUMBER:'/get_all_membership_kyc_details_by_admission_number',
    GET_ALL_KYC_BY_APPLICATION_ID:'/get_all_sao_loan_kyc_details_by_loan_application_id',
    MEMBER_ACCOUNT_BALANCES: '/member_account_balances',
    GET_MEMBER_INSTITUTION_DETAILS_BY_ID_AND_PACS_ID: '/get_member_institution_details_by_id_and_pacsid',
    KYC_DOC_TYPES: '/kyc_doc_types',
    SAVE_KYC_LIST:'/save_kyc_details_list',
    INSTITUTION_WORKFLOW_HISTORY: '/institution_workflow_history',
    INSTITUTION_WORK_FLOW: '/institution_work_flow',
    INSTITUTION_PROMOTER_KYC_DETAILS: '/institution_promoter_kyc_details',
    GET_PROMOTER_KYC_DETAILS_BY_INSTITUTE_ID_PROMOTER_ID_AND_PACS_ID: '/get_promoter_kyc_details_by_instituteId_promoterid_and_pacsId',
    GET_INSTITUTION_PROMOTER_DETAILS_BY_INSTITUTION_ID_AND_PACS_ID: '/get_insititution_promoter_details_by_institutionId_and_pacsId',
    INSTITUTION_COMMUNICATION: '/institution_communication',
    GET_INSTITUTION_COMMUNICATION_DETAILS_BY_INSTITUTION_ID: '/get_institution_communication_details_by_institution_id',
    GROUP_WORKFLOW_HISTORY: '/group_workflow_history',
    GROUP_WORK_FLOWS: '/group_work_flows',
    GET_GROUP_PROMOTER_DETAILS_BY_GROUP_ID: '/get_group_promoter_details_by_group_id',
    GROUP_PROMOTER_KYC_DETAILS: '/group_promoter_kyc_details',
    GET_GROUP_KYC_DETAILS_BY_GROUPID_AND_PACSID: '/get_group_kyc_details_by_groupId_and_pacsId',
    GROUP_KYC_DETAILS: '/group_kyc_details',
    GET_GROUP_KYC_DETAILS_BY_GROUP_ID_AND_PACS_ID: '/get_group_kyc_details_by_group_id_and_pacs_id_and_branch_id',
    GROUP_COMMUNICATION_DETAILS: '/group_communication_details',
    GET_GROUP_COMMUNICATION_DETAILS_BY_GROUP_ID: '/get_group_communication_details_by_group_id',
    WORK_FLOW_STEPS: '/work_flow_steps',
    WORK_FLOW_RESOURCE: '/work_flow',
    VILLAGES: '/villages',
    GET_VILLAGES_BY_SUB_DISTRICT_ID: '/get_villages_by_sub_district_id',
    TRANSACTIONS_MODES: '/transaction_modes',
    TERM_ACCOUNT_INSTALLMENTS: '/term_account_installments',
    ADD_INSTALLMENT_WITH_TRANSACTION: '/add_installment_with_transaction',
    GET_LIST_ACCOUNT_WITH_DUE_INSTALLMENTS_WITH_TRANSACTIONS_LIST: '/get_list_account_with_due_intallments_with_transaction_list',
    GET_LIST_ACCOUNT_WITH_DUE_INSTALLMENTS_WITH_ALL_TRANSACTIONS_LIST: '/get_list_account_with_due_intallments_with_All_transaction_list',
    GET_LIST_ACCOUNT_WITH_DUE_INSTALLMENTS: '/get_list_account_with_due_intallments',
    GET_LIST_ACCOUNT: '/get_list_account',
    TD_FORM_TYPES: '/td_form_types',
    TD_CASH_TRANSACTION_DENOMINATION: '/td_cash_transaction_denominations',
    SUB_DISTRICT: '/sub_district',
    GET_SUB_DISTRICTS_BY_ID: '/get_sub_districts_by_district_id',
    STATES: '/states',
    DISTRICT:'/district',
    GET_DISTRICT_BY_STATE_ID:'/get_district_by_state_id',
    GET_STATE_BY_COUNTRY_ID: '/get_state_by_country_id',
    SOCIETY_BRANCHES: '/society_branches',
    SETTINGS: '/settings',
    SERVICE_TYPES: '/service_types',
    RELATIONSHIP_TYPES: '/relationship_types',
    REASON: '/reason',
    RD_REQUIRED_DOCUMENT_CONFIG: '/rd_required_documents_config',
    RD_PRODUCT_DEFINITION: '/rd_product_definition',
    GET_PRODUCT_OVERVIEW_BY_ID: '/get_product_overview_by_id',
    GET_APPROVED_RD_PRODUCT_DEFINITION: '/get_approved_rd_product_definition',
    RD_PENALTY_CONFIGS: '/rd_penalty_configs',
    RD_JOINT_ACC_HOLDER_DETAILS: '/rd_joint_acc_holder_details',
    RD_INTEREST_POLICY_CONFIG: '/rd_interest_policy_config',
    RD_FAS: '/rd_fas',
    RD_ACCOUNT_TRANSACTIONS: '/rd_accounts_transactions',
    FD_CUMMULATIVE_ACCOUNTS: '/fd_cummulative_accounts',
    RD_ACCOUNTS: '/rd_accounts',
    SB_INTEREST_CALCULATION: '/sb_interest_calculation',
    SAVE_RD_INSTALLMENTS_ON_ACCOUNT_APPROVAL: '/save_rd_installments_on_account_approval',
    SAVE_RD_ACCOUNT_ON_CLOSURE_OR_FORE_CLOSURE: '/save_rd_account_on_closure_or_fore_closure',
    SAVE_ACCOUNT_ON_RENEWAL: '/save_account_on_renewal',
    GET_RD_MATURITY_AMOUNT_ON_FORECLOSURE: '/get_rd_maturity_amount_on_foreclosure',
    GET_RD_MATURITY_AMOUNT_ON_CLOSURE: '/get_rd_maturity_amount_on_closure',
    GET_RD_INTEREST_POLICY_CONFIG: '/get_rd_interest_policy_config',
    GET_RD_TRNASACTIONS_BY_ACCOUNT_ID_AND_TRANSACTION_TYPE: '/get_rd_transactions_by_account_id_and_transaction_type',
    GET_RD_INSTALLMENTS_BY_ACCOUNT_ID: '/get_rd_installments_by_account_id',
    GET_RD_ACCOUNTS_WITH_ALL_INSTALLMENTS_AND_TRANSACTIONS: '/get_rd_accounts_with_all_instalments_and_transactions',
    GET_RD_ACCOUNTS_BY_PACS_AND_BRANCHID: '/get_rd_accounts_by_pacsid_and_branchid',
    GET_RD_ACCOUNT_DETAILS_BY_ADMISSION_NUMBER_AND_ID: '/get_rd_account_details_by_admission_number_and_id',
    RD_ACCOUNT_NOMINEES: '/rd_account_nominees',
    GET_NOMINEE_BY_TERM_ACCOUNT_ID: '/get_nominee_by_term_account_id',
    RD_ACCOUNT_KYC: '/rd_account_kyc',
    GET_KYC_DETAILS_BY_TERM_ACCOUNT_ID: '/get_kyc_details_by_term_account_id',
    GET_ALL_RD_ACC_KYC_DETAILS_BY_ADMISSION_NUMBER:'/get_all_rd_acc_kyc_details_by_admission_number',
    GET_BY_ACCOUNT_ID_AND_NUMBER_ID_AND_MEMBER_TYPE: '/get_by_account_id_and_member_id_and_member_type',
    GET_BY_ACCOUNT_ID_AND_MEMBER_ID_AND_ADMISSION_NUMBER: '/get_by_account_id_and_member_id_and_admission_number',
    RD_ACCOUNT_GUARDIAN: '/rd_account_guardian',
    GET_GUARDIAN_DETAILS_BY_TERM_ACCOUNT_ID: '/get_gaurdian_details_by_term_account_id',
    RD_ACCOUNT_COMMUNICATION: '/rd_account_communication',
    GET_COMMUNICATION_DETAILS_RD_ACCOUNT_ID_AND_MEMBER_ID_AND_MEMBER_TYPE: '/get_communication_details_by_rd_account_id_and_member_id_and_member_type',
    GET_COMMUNICATION_DETAILS_BY_RD_ACCOUNT_ID_AND_COMMUNICATION_TYPE_AND_ADMISSION_NUMBER: '/get_communication_details_by_rd_account_id_and_communicationType_and_admissionNumber',
    GET_COMMUNICATION_BY_TERM_ACCOUNT_ID: '/get_communication_by_term_account_id',
    GET_REQUIRED_DOCUMENT_DETAILS_BY_ACC_ID_AND_MEMBER_TYPE_AND_MEMBER_ID:'/get_required_document_details_by_acc_id_and_member_type_and_member_id',
    GET_REQUIRED_DOCUMENT_DETAILS_BY_ACC_ID_AND_MEMBER_TYPE_AND_ADMISSION_NUMBER:'/get_required_document_details_by_acc_id_and_member_type_and_admission_number',
    QUALIFICATION: '/qualification',
    PRODUCT_TYPES: '/product_types',
    TERM_TRANSFER_TRANSACTION_DETAILS: '/term_transfer_transaction_details',
    TERM_TRANSACTION_DETAILS: '/term_transaction_details',
    GET_ALL_TRANSACTION_DETAILS_BY_MODULE_TYPE: '/get_all_transaction_details_by_module_type',
    GET_ALL_TRANSACTION_DETAILS_BY_LOAN_APPLICATION_ID: '/get_all_transaction_details_by_loan_application_id',
    TERM_STORAGE_MORTGAGE_DETAILS: '/term_storage_mortgage_details',
    TERM_REQUIRED_DOCUMENTS_CONFIGS: '/term_required_documents_configs',
    TERM_PRODUCT_DEFINITIONS: '/term_product_definitions',
    GET_TERM_PRODUCT_DEFINITION_PREVIEW_BY_PRODUCT_ID: '/get_term_product_definition_preview_by_prod_id',
    TERM_PRODUCT_CHARGES_CONFIGS: '/term_product_charges_configs',
    GET_PRODUCT_CHARGES_DETAILS_BY_APPLICABLE_DURING: '/get_product_charges_details_by_applicable_during',
    GET_CALCULATED_SANCTION_AMOUNT: '/get_calculated_sanction_amount',
    TERM_PROD_PURPOSE_CONFIGS: '/term_prod_purpose_configs',
    TERM_PRODUCT_COLLATERALS_CONFIGS: '/term_prod_collaterals_configs',
    TERM_OTHER_MORTGAGE_DETAILS: '/term_other_mortgage_details',
    TERM_OTHER_LOAN_DETAILS: '/term_other_loan_details',
    GER_TERM_OTHER_LOANS_DETAILS_BY_TERM_LOAN_APPLICATION_ID: '/get_term_other_loans_details_by_term_loan_application_id',
    TERM_MORTGAGE_DETAILS_SUMMARIES: '/term_mortgage_details_summaries',
    TERM_LOAN_INSURANCE_DETAILS: '/term_lona_insurance_details',
    TERM_LOAN_VEHICLE_MORTGAGE_DETAILS: '/term_loan_vehicle_mortgage_details',
    TERM_LOAN_OUTSTANDING_DETAILS: '/term_loan_outstanding_details',
    TERM_LOAN_NOTICE_DETAILS: '/term_loan_notice_details',
    GET_TERM_NOTICE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_term_notice_details_by_loan_application_id',
    TERM_LOAN_NOMINEE_DETAILS: '/term_loan_nominee_details',
    TERM_LOAN_LINKED_SHARECAPITAL_CONFIGS: '/term_loan_linked_sharecapital_configs',
    TERM_LOAN_LAND_MORTGAGE_DETAILS: '/term_loan_land_mortgage_details',
    TERM_LOAN_GUARANTOR_DETAILS: '/term_loan_guarantor_details',
    TERM_LOAN_GOLD_MORTGAGE_DETAILS: '/term_loan_gold_mortgage_details',
    TERM_LOAN_GENEALOGY_TREE: '/term_loan_genealogy_tree',
    GET_TERM_GENEALOGY_TREE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_term_genealogy_tree_details_by_loan_application_id',
    TERM_LOAN_DOCUMENTS_DETAILS: '/term_loan_documents_details',
    TERM_LOAN_DISBURSEMENT_SCHEDULE: '/term_loan_disbursement_schedule',
    GET_CI_LOAN_DISBURSEMENT_SCHEDULE_BY_LOAN_APPLICATION_ID: '/get_ci_loan_disbursement_schedule_by_loan_application_id',
    TERM_LOAN_CO_APPLICANT_DETAILS: '/term_loan_co_applicant_details',
    GET_TERM_LOAN_CO_APPLICANT_BY_LOAN_APPLICATION_ID: '/get_term_loan_co_applicant_by_loan_application_id',
    TERM_LOAN_CHARGES_DETAILS: '/term_loan_charges_details',
    TERM_LOAN_APPRAISER_DETAILS: '/term_loan_appraiser_details',
    TERM_LOAN_APPLICATIONS: '/term_loan_applications',
    TERM_LOAN_APPLICATION_APPROVAL: '/ term_loan_applcation_approval',
    CONVERT_SAO_LOAN_TO_TERM_LOAN: '/convert_sao_loan_to term_loan',
    GET_TERM_LOAN_APPLICATION_DETAILS_BY_ID: '/get_term_loan_application_details_by_id',
    TERM_INTEREST_POLICY_CONFIGS: '/term_interest_policy_configs',
    TERM_FORECLOSURE_DETAILS: "/term_foreclosure_details",
    GET_BY_LOAN_APPLICATION_ID: '/get_by_laon_application_id',
    TERM_FIELD_VERIFICATION_DETAILS: '/term_field_verification_details',
    GET_TERM_FIELD_VERIFICATION_DETAILS_BY_LOAN_APPLICATION_ID: '/get_term_field_verification_details_by_loan_application_id',
    TERM_DISBURSEMENTS: '/term_disbursements',
    TERM_DISBURSEMENT_APPROVAL: '/term_disbursement_approval',
    TERM_COLLECTIONS: '/term_collections',
    APPROVAL_TERM_COLLECTION_DETAILS: '/approval_term_collection_details',
    GET_DEMAND_BY_ACCOUNT_NUMBER: '/get_demand_by_account_number',
    TERM_CHEQUE_TRANSACTION_DETAILS: '/term_cheque_transaction_details',
    TERM_CHARGES_COLLECTION_DETAILS: '/term_charges_collection_details',
    TERM_CASH_TRANSACTION_DENOMINATIONS: '/term_cash_transaction_denominations',
    TERM_BONDS_MORTGAGE_DETAILS: '/term_bonds_mortgage_details',
    TERM_APPORTION_CONFIGS: '/term_apportion_configs',
    TERM_ACCOUNT_LEDGER_DETAILS: '/term_account_ledger_details',
    SI_TRANSFER_TRANSACTION_DETAILS: '/si_transfer_transaction_details',
    SI_TRANSACTION_DETAILS: '/si_transaction_details',
    SI_STORAGE_LOAN_MORTGAGE_DETAILS: '/si_storage_mortgage_details',
    GET_DETAILS_BY_SI_LOAN_APPLICATION_ID: '/get_details_by_si_loan_application_id',
    SI_REQUIRED_DOCUMENTS_CONFIG: '/si_required_documents_config',
    GET_SI_REQUIRED_DOCUMENTS_CONFIG_BY_SI_PRODUCT_ID: '/get_si_required_documents_config_by_si_product_id',
    SI_PRODUCT_DEFINITION: '/si_product_definition',
    GET_SI_PRODUCT_DEFINITION_PREVIEW_BY_PROD_ID: '/get_si_product_definition_preview_by_prod_id',
    SI_PRODUCT_CHARGES_CONFIG: '/si_product_charges_config',
    GET_SI_PRODUCT_CHARGES_CONFIG_BY_SI_PRODUCT_ID: '/get_si_product_charges_config_by_si_product_id',
    GET_SI_CHARGES_DETAILS_BY_APPLICABLE_DURING: '/get_si_charges_details_by_applicable_during',
    GET_SI_PROD_PURPOSE_CONFIG_BY_SI_PRODUCT_ID: '/get_si_prod_purpose_config_by_si_product_id',
    SI_PROD_PURPOSE_CONFIG: '/si_prod_purpose_config',
    SI_PROD_COLLATERALS_CONFIG: '/si_prod_collaterals_config',
    GET_SI_PROD_COLLATERALS_CONFOG_BY_SI_PRODUCT_ID: '/get_si_prod_collaterals_config_by_si_product_id',
    SI_OTHER_LOAN_MORTGAGE_DETAILS: '/si_other_mortgage_details',
    SI_OTHER_LOAN_DETAILS: '/si_other_loan_details',
    GET_SI_OTHER_LOANS_DETAILS_BY_LOAN_APPLICATION_ID: '/get_si_other_loans_details_by_loan_application_id',
    SI_MORTGAGE_DETAILS_SUMMARIES: '/si_mortgage_details_summaries',
    SI_VEHICLE_LOAN_MORTGAGE_DETAILS: '/si_loan_vehicle_mortgage_details',
    SI_LOAN_OUTSTANDING_DETAILS: '/si_loan_outstanding_details',
    SI_LOAN_NOTICE_DETAILS: '/si_loan_notice_details',
    GET_SI_NOTICE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_si_notice_details_by_loan_application_id',
    SI_LOAN_NOMINEE_DETAILS: '/si_loan_nominee_details',
    FILES: '/files/files',
    SI_LOAN_LINKED_SHARE_CAPITAL_CONFIG: '/si_loan_linked_share_capital_config',
    GET_SI_LOAN_LINKED_SHARECAPITAL_CONFOG_BY_SI_PRODUCT_ID: '/get_si_loan_linked_sharecapital_config_by_si_product_id',
    SI_LOAN_LAND_MORTGAGE_DETAILS: '/si_loan_land_mortgage_details',
    SI_LOAN_INSURANCE_DETAILS: '/si_loan_insurance_details',
    SI_LOAN_GUARANTOR_DETAILS: '/si_loan_guarantor_details',
    SI_LOAN_GOLD_MORTGAGE_DETAILS: '/si_loan_gold_mortgage_details',
    SI_LOAN_GENEALOGY_TREE: '/si_loan_genealogy_tree',
    GET_SI_GENEALOGY_TREE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_si_genealogy_tree_details_by_loan_application_id',
    SI_LOAN_DOCUMENT_DETAILS: '/si_loan_documents_details',
    SI_LOAN_DISBURSEMENT_SCHEDULE: '/si_loan_disbursement_schedule',
    GET_SI_LOAN_DISBURSEMENT_SCHEDULE_BY_LOAN_APPLICATION_ID: '/get_si_loan_disbursement_schedule_by_loan_application_id',
    SI_LOAN_CO_APPLICANT_DETAILS: '/si_loan_co_applicant_details',
    GET_SI_LOAN_CO_APPLICANT_BY_LOAN_APPLICATION_ID: '/get_si_loan_co_applicant_By_loan_application_id',
    SI_LOAN_CHARGES_DETAILS: '/si_loan_charges_details',
    SI_LOAN_APPRAISER_DETAILS: '/si_loan_appraiser_details',
    SI_LOAN_APPLICATION: '/si_loan_application',
    GET_LOAN_APPLICATION_DETAILS_BY_LOAN_APPLICATION_ID: '/get_loan_application_details_by_loan_application_id',
    SI_INTEREST_POLICY_CONFIGS: '/si_interest_policy_configs',
    GET_SI_INTEREST_POLICY_CONFIG_BY_SI_PRODUCT_ID: '/get_si_interest_policy_config_by_si_product_id',
    SI_FORECLOSURE_DETAILS: '/si_foreclosure_details',
    GET_BY_APPLICATION_ID: '/get_by_application_id',
    SI_FIELD_VERIFICATION_DETAILS: '/si_field_verification_details',
    GET_SI_FIELD_VERIFICATION_DETAILS_BY_LOAN_APPLICATION_ID: '/get_si_field_verification_details_by_loan_application_id',
    SI_DISBURSEMENT: '/si_disbursement',
    GET_SI_DISBURSEMENT_LIST_BY_APPLICATION_ID: '/get_si_disbursement_list_by_application_id',
    SI_COLLECTION: "/si_collection",
    APPROVAL_SI_COLLECTION_DETAILS: '/approval_si_collection_details',
    GET_DEMAND: '/get_demand',
    GET_COLLECTION_LIST_BY_APPLICATION_ID:'/get_sao_loan_collections_by_application_id',
    SI_CHEQUE_TRANSACTION_DETAILS: '/si_cheque_transaction_details',
    SI_CHARGES_COLLECTION_DETAILS: '/si_charges_collection_details',
    SI_CASH_TRANSACTION_DENOMINATION: '/si_cash_transaction_denomination',
    SI_BOND_LOAN_MORTGAGE_DETAILS: '/si_bonds_mortgage_details',
    SI_APPORTION_CONFIG: '/si_apportion_config',
    GET_SI_APPORTION_CONFIG_BY_SI_PRODUCT_ID: '/get_si_apportion_config_by_si_product_id',
    SI_ACCOUNT_LEDGER_DETAILS: '/si_account_ledger_details',
    OPERATOR_TYPES: '/operation_types',
    OCCUPATION_TYPES: '/occupation_types',
    MEMBER_TYPES: '/member_types',
    INTEREST_PAYMENTS: '/interest_payments',
    GET_ALL_PAYMENTS_BY_ACCOUNT_ID_AND_ACCOUNT_NUMBER:'/get_all_payments_by_account_id_and_account_number',
    SAVE_INTEREST_PAYMENT_LIST: '/save_interest_payment_list',
    GET_TRANSACTION_LIST_BASED_ON_ACCOUNT_WITH_DUE_INTEREST_PAYMENTS: '/get_transaction_list_based_on_account_with_due_interest_payments',
    GET_ALL_TRANSACTION_LIST_WITH_INTEREST_PAYMENT_DETAILS: '/get_all_transaction_list_with_interest_payment_details',
    INTEREST_PAYMENT_SUMMARY: '/interest_payment_summary',
    GET_INTEREST_POSTING_DETAILS_BY_ID: '/get_interest_posting_details_by_id',
    INTEREST_PAYMENT_FREQUENCY: '/interest_payment_frequency',
    INISTITUTION_PROMOTER_DETAILS: '/institution_promoter_details',
    GET_INISTITUTION_PROMOTER_DETAILS_BY_INISTITUTIONID_AND_PACSID: '/get_insititution_promoter_details_by_institutionId_and_pacsId',
    FD_NON_CUMMULATIVE_REQUIRED_DOCUMENTES_CONFIG: '/fd_non_cummulative_required_documents_config',
    FD_NON_CUMMULATIVE_PRODUCT_DEFINITION: '/fd_non_cummulative_product_definition',
    FD_NON_CUMMULATIVE_JOINT_ACC_HOLDER_DETAILS: '/fd_non_cummulative_joint_acc_holder_details',
    FD_NON_CUMMULATIVE_INTEREST_POLICY_CONFIG: '/fd_non_cummulative_interest_policy_config',
    FD_NON_CUMMULATIVE_FAS: '/fd_non_cummulative_fas',
    FD_NON_CUMMULATIVE_ACCOUNTS_TRANSACTIONS: '/fd_non_cummulative_accounts_transactions',
    FD_NON_CUMMULATIVE_ACCOUNTS: '/fd_non_cummulative_accounts',
    FD_CUMULATIVE_ACCOUNTS_TRANSACTION:'/fd_cummulative_accounts_transactions',
    RD_ACCOUNTS_TRANSACTIONS:'/rd_accounts_transactions',
    UPDATE_CLOUSER_STATUS: '/update_clouser_status',
    GET_FD_NON_CUMMULATIVE_TRANSACTIONS_BY_ACCOUNT_ID_AND_TRANSACTION_TYPE: '/get_fd_non_cummulative_transactions_by_account_id_and_transaction_type',
    GET_FD_NON_CUMMULATIVE_ACCOUNT_DETAILS: '/get_fd_non_cummulative_account_details',
    GET_ALL_FD_NON_CUMMULATIVE_BY_BRANCH_ID_PACS_ID: '/get_all_fd_non_cummulative_by_branchId_pacsId',
    GET_ACCOUNT_DETAILS_BY_ADMISSION_NUMBER_AND_ID: '/get_account_details_by_admission_number_and_id',
    SAVE_FORE_CLOSURE_DETAILS: '/save_fore_closure_details',
    SAVE_FD_NON_CUMMULATIVE_INSTALLMENTS_ON_ACCOUNT_APPROVAL: '/save_fd_non_cummulative_installments_on_account_approval',
    GET_FD_NON_CUMMULATIVE_INTEREST_POLICY_CONFIG: '/get_fd_non_cummulative_interest_policy_config',
    FD_NON_CUMMULATIVE_ACCOUNT_NOMINEES: '/fd_non_cummulative_account_nominees',
    FD_NON_CUMMULATIVE_ACCOUNT_KYC: '/fd_non_cummulative_account_kyc',
    GET_KYC_BY_ACCOUNT_ID_AND_MEMBER_ID_AND_MEMBER_TYPE: '/get_kyc_by_account_id_and_member_id_and_member_type',
    GET_KYC_BY_ACCOUNT_ID_AND_MEMBER_ID_AND_ADMISSION_NUMBER: '/get_kyc_by_account_id_and_member_id_and_admission_number',
    FD_NON_CUMMULATIVE_ACCOUNT_GUARDIAN: '/fd_non_cummulative_account_guardian',
    FD_NON_CUMMULATIVE_ACCOUNT_COMMUNICATION: '/fd_non_cummulative_account_communication',
    GET_COMMUNICATION_DETAILS_BY_FD_NON_CUMMLATIVE_ACCOUNT_ID_AND_MEMBER_ID: '/get_communication_details_by_fd_non_cummlative_account_id_and_member_id',
    GET_COMMUNICATION_DETAILS_BY_FD_NON_CUMMLATIVE_ACCOUNT_ID_AND_COMMUNICATION_TYPE: '/get_communication_details_by_fd_non_cummlative_account_id_and_communicationType',
    GET_COMMUNICATION_DETAILS_BY_FD_NON_CUMMLATIVE_ACCOUNT_ID_AND_ADMISSION_NUMBER: '/get_communication_details_by_fd_non_cummlative_account_id_and_admission_number',
    CARD_RATES: '/card_rates',
    GET_CARD_RATES_BY_PACS_ID: '/get_card_rates_by_pacs_id',
    SAO_TRANSFER_TRANSACTION_DETAILS: '/sao_transfer_transaction_details',
    SAO_TRANSACTION_DETAILS: '/sao_transaction_details',
    GET_ALL_TRANSACTION_DETAILS_DETAILS_BY_MODULE_TYPE: '/get_all_transaction_details_details_by_module_type',
    SAO_REQUIRED_DOCUMENTS_CONFIG: '/sao_required_documents_config',
    SAO_PRODUCT_DEFINITIONS: '/sao_product_definitions',
    GET_PREVIEW_DETAILS_BY_PRODUCT_ID: '/get_preview_details_by_product_id',
    SAO_PRODUCT_CHARGES_CONFIG: '/sao_product_charges_config',
    GET_SAO_PRODUCT_CHARGES_DETAILS_BY_APPLICABLE_DURING: '/get_sao_product_charges_details_by_applicable_during',
    SAO_PROD_PURPOSE_CONFIG: '/sao_prod_purpose_config',
    SAO_PROD_COLLATERALS_CONFIG: '/sao_prod_collaterals_config',
    SAO_OTHER_LOAN_DETAILS: '/sao_other_loan_details',
    GET_SAO_OTHER_LOANS_DETAILS_BY_LOAN_APPLICATION_ID: '/get_sao_other_loans_details_by_loan_application_id',
    SAO_MORTGAGE_DETAILS_SUMMARY: '/sao_mortgage_details_summary',
    SAO_LOAN_SUBSIDY_DETAILS: '/sao_loan_subsidy_details',
    SAO_LOAN_OUTSTANDING_DETAILS: '/sao_loan_outstanding_details',
    SAO_LOAN_NOTICE_DETAILS: '/sao_loan_notice_details',
    GET_SAO_NOTICE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_sao_notice_details_by_loan_application_id',
    SAO_LOAN_NOMINEE_DETAILS: '/sao_loan_nominee_details',
    SAO_LOAN_LINKED_SHARECAPITAL_CONFIG: '/sao_loan_linked_sharecapital_config',
    SAO_LOAN_LAND_MORTAGE_DETAILS: '/sao_loan_land_mortage_details',
    SAO_LOAN_JOINT_MEMS_DETAILS: '/sao_loan_joint_mems_details',
    GET_SAO_LOAN_JOINT_MEMS_DETAILS_BY_LOAN_APPLICATION_ID: '/get_sao_loan_joint_mems_details_by_loan_application_id',
    SAO_LOAN_INSURANCE_DETAILS: '/sao_loan_insurance_details',
    GET_INSURENCE_DETAILS_BY_APPLICATION_ID:'/get_insurence_details_by_loan_application_id',
    SAO_LOAN_GUARANTOR_DETAILS: '/sao_loan_guarantor_details',
    SAO_LOAN_GENEALOGY_TREE: '/sao_loan_genealogy_tree',
    GET_NOMINEE_DETAILS_BY_APPLICATION_ID:'/get_sao_loan_nominee_details_by_application_id',
    GET_SAO_GENEALOGY_TREE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_sao_genealogy_tree_details_by_loan_application_id',
    SAO_LOAN_DOCUMENTS_DETAILS: '/sao_loan_documents_details',
    SAO_LOAN_DISBURSEMENT_SCHEDULE: '/sao_loan_disbursement_schedule',
    SAO_FIELD_VISIT:'/sao_loan_field_visit_config',
    GET_SAO_LOAN_DISBURSEMENT_SCHEDULE_BY_LOAN_APPLICATION_ID: '/get_sao_loan_disbursement_schedule_by_loan_application_id',
    SAO_LOAN_CHARGES_DETAILS: '/sao_loan_charges_details',
    SAO_LOAN_APPRAISER_DETAILS: '/sao_loan_appraiser_details',
    SAO_LOAN_APPLICATION: '/sao_loan_application',
    SAO_LOAN_APPLICATION_PDF_DOWNLOAD:'/sao_loan_application_preview_download',
    TERM_LOAN_APPLICATION_PDF_DOWNLOAD:'/term_loan_application_preview_download',
    SAO_LOAN_APPLICATION_APPROVAL: '/sao_loan_application_approval',
    GET_SAO_LOAN_APPLICATION_DETAILS_BY_ID: '/get_sao_loan_application_details_by_id',
    SUBMIT_FOR_APPROVAL:'/submit_for_approval',
    GET_SAO_LOAN_APPLICATION_DETAILS_BY_PACS_ID_AND_BRANCH_ID: '/get_sao_loan_applications_by_pacs_id_and_branch_id',
    GET_CI_LOAN_APPLICATION_DETAILS_BY_PACS_ID_AND_BRANCH_ID:'/get_ci_loan_applications_by_pacs_id_and_branch_id',
    SAO_INTEREST_POLICY_CONFIGS: '/sao_interest_policy_configs',
    SAO_GL_HEAD_MAPPING: '/sao_gl_head_mapping',
    GET_GL_HEAD_MAPPING_DETAILS_BY_PRODUCT_ID: '/get_gl_head_mapping_details_by_product_id',
    SAO_FORECLOSURE_DETAILS: '/sao_foreclosure_details',
    SAO_FIELD_VERIFICATION_DETAILS: '/sao_field_verification_details',
    GET_SAO_FIELD_VERIFICATION_DETAILS_BY_LOAN_APPLICATION_ID: '/get_sao_field_verification_details_by_loan_application_id',
    SAO_DISBURSEMENT: '/sao_disbursement',
    SAO_DISBURSEMENT_APPROVAL: '/sao_disbursement_approval',
    SAO_COLLECTION: '/sao_collection',
    APPROVE_SAO_COLLECTION_DETAILS: '/approve_sao_collection_details',
    SAO_CHEQUE_TRANSACTION_DETAILS: '/sao_cheque_transaction_details',
    SAO_CHARGES_COLLECTION_DETAILS: '/sao_charges_collection_details',
    SAO_CASH_TRANSACTION_DENOMINATION: '/sao_cash_transaction_denomination',
    SAO_APPORTION_CONFIG: '/sao_apportion_config',
    SAO_ACCOUNT_LEDGER_DETAILS: '/sao_account_ledger_details',
    GET_SAO_LOAN_DOCUMENT_DETAILS_BY_ID:'/get_sao_documents_details_by_application_id',
    GET_SAO_LAND_DETAILS_BY_LOAN_ID:'/get_land_mortgage_details_by_loan_application_id',
    GET_SPEACIAL_SCHEME_MATURITY_AMOUNT_ON_CLOSURE: '/get_special_scheme_maturity_amount_on_closure',
    GET_MATURITY_AMOUNT_ON_FORECLOSURE: '/get_maturity_amount_on_foreclosure',
    GET_MATURITY_AMOUNT_ON_CLOSURE: '/get_maturity_amount_on_closure',
    GET_FD_CUMMULATIVE_INTEREST_POLICY_CONFIG: '/get_fd_cummulative_interest_policy_config',
    FD_CUMMULATIVE_ACCOUNT_CLOSURE_OR_FORECLOSURE: '/fd_cummulative_account_closure_or_foreclosure',
    GET_TRANSACTIONS_BY_ACCOUNT_ID_AND_TRANSACTION_TYPE: '/get_transactions_by_account_id_and_transaction_type',
    GET_FD_CUMMULATIVE_ACCOUNTS_BY_PACSID_BRANCHID: '/get_fd_cummulative_accounts_by_pacsid_and_branchid',
    GET_ALL_TRANSACTIONS_BY_FD_ACCOUNT_ID: '/get_all_transactions_by_fd_account_id',
    DEPOSITER_TRANSFER_TRANSACTION_DETAILS: '/depositor_transfer_transaction_details',
    DEPOSITER_TRANSACTION_DETAILS: '/depositor_transaction_details',
    DEPOSITER_REQUIRED_DOCUMENTS_CONFIGS: '/depositor_required_documents_configs',
    GET_DEPOSITER_REQUIRED_DOCUMENTS_CONFIG_BY_CI_PRODUCT_ID: '/get_depositor_required_documents_config_by_ci_product_id',
    DEPOSITOR_PRODUCT_DEFINITIONS: '/depositor_product_definitions',
    GET_DEPOSITER_PRODUCT_DEFINITION_BY_PRODUCT_ID: '/get_depositor_product_definition_by_product_id',
    DEPOSITER_PRODUCT_CHARGES_CONFIG: '/depositor_product_charges_configs',
    GET_DEPOSITER_PRODUCT_CHARGES_DETAILS_BY_APPLICABLE_DURING: '/get_depositor_product_charges_details_by_applicable_during',
    GET_DEPOSITER_PRODUCT_CHARGES_CONFIG_BY_CI_PRODUCT_ID: '/get_depositor_product_charges_config_by_ci_product_id',
    DEPOSITER_PROD_COLLATERALS_CONFIGS: '/depositor_prod_collaterals_configs',
    GET_DEPOSITER_PROD_COLLATERALS_CONFIG_BY_CI_PRODUCT_ID: '/get_depositor_prod_collaterals_config_by_ci_product_id',
    DEPOSITOR_MORTGAGE_DETAILS_SUMMARIES: '/depositor_mortgage_details_summaries',
    DEPOSITOR_LOAN_OUTSTANDING_DETAILS: '/depositor_loan_outstanding_details',
    DEPOSITER_LOAN_NOMINEE_DETAILS: '/depositor_loan_nominee_details',
    DEPOSITER_LOAN_LINKED_SHARECAPITAL_CONFIGS: '/depositor_loan_linked_sharecapital_configs',
    GET_DEPOSITOR_LOAN_LINKED_SHARECAPITAL_CONFIG_BY_CI_PRODUCT_ID: '/get_depositor_loan_linked_sharecapital_config_by_ci_product_id',
    DEPOSITER_LOAN_DOCUMENTS_DETAILS: '/depositor_loan_documents_details',
    DEPOSITER_LOAN_DISBURSEMENT_SCHEDULES: '/depositor_loan_disbursement_schedules',
    GET_DEPOSITER_LOAN_DISBURSEMENT_SCHEDULE_BY_LOAN_APPLICATION_ID: '/get_depositor_loan_disbursement_schedule_by_loan_application_id',
    DEPOSITER_LOAN_CO_APPLICANT_DETAILS: '/depositor_loan_co_applicant_details',
    GET_DEPOSITER_LOAN_CO_APPLICANT_BY_LOAN_APPLICATION_ID: '/get_depositor_loan_co_applicant_by_loan_application_id',
    DEPOSITOR_LOAN_APPLICATIONS: '/depositor_loan_applications',
    DEPOSITOR_LOAN_APPLICATION_APPROVAL: '/depositor_loan_application_approval',
    DEPOSITOR_INTEREST_POLICY_CONFIGS: '/depositor_interest_policy_configs',
    GET_DEPOSITER_INTEREST_POLICY_CONFIG_BY_CI_PRODUCT_ID: '/get_depositor_interest_policy_config_by_ci_product_id',
    DEPOSITER_DISBURSEMENTS: '/depositor_disbursements',
    DEPOSITER_DISBURSEMENT_APPROVAL: '/depositor_disbursement_approval',
    DEPOSITOR_COLLECTIONS: '/depositor_collections',
    APPROVAL_CI_COLLECTION_DETAILS: '/approval_ci_collection_details',
    DEPOSITOR_CHEQUE_TRANSACTION_DETAILS: '/depositor_cheque_transaction_details',
    DEPOSITOR_CHARGES_COLLECTION_DETAILS: '/depositor_charges_collection_details',
    DEPOSITOR_CASH_TRANSACTION_DENOMINATION: '/depositor_cash_transaction_denomination',
    DEPOSITOR_BONDS_MORTGAGE_DETAILS: '/depositor_bonds_mortgage_details',
    GET_DETAILS_BY_DEPOSITOR_LOAN_APPLICATION_ID: '/get_details_by_depositor_loan_application_id',
    DEPOSITOR_APPORTION_CONFIGS: '/depositor_apportion_configs',
    GET_DEPOSITOR_APPORTION_CONFIG_BY_CI_PRODUCT_ID: '/get_depositor_apportion_config_by_ci_product_id',
    DEPOSITOR_ACCOUNT_LEDGER_DETAILS: '/depositor_account_ledger_details',
    CI_TRANSFER_TRANSACTION_DETAILS: '/ci_transfer_transaction_details',
    CI_TRANSACTION_DETAILS: '/ci_transaction_details',
    CI_STORAGE_MORTGAGE_DETAILS: '/ci_storage_mortgage_details',
    GET_DETAILS_BY_CI_LOAN_APPLICATION_ID: '/get_details_by_ci_loan_application_id',
    CI_REQUIRED_DOCUMENTS_CONFIGS: '/ci_required_documents_configs',
    GET_CI_REQUIRED_DOCUMENTS_CONFIG_BY_CI_PRODUCT_ID: '/get_ci_required_documents_config_by_ci_product_id',
    CI_PRODUCT_DEFINITIONS: '/ci_product_definitions',
    GET_CI_PRODUCT_DEFINITION_BY_PRODUCT_ID: '/get_ci_product_definition_by_product_id',
    CI_PRODUCT_CHARGES_CONFIG: '/ci_product_charges_configs',
    GET_CI_PRODUCT_CHARGES_DETAIKLS_BY_APPLICABLE_DURING: '/get_ci_product_charges_details_by_applicable_during',
    GET_CI_PRODUCT_CHARGES_CONFIG_BY_CI_PRODUCT_ID: '/get_ci_product_charges_config_by_ci_product_id',
    CI_PROD_PURPOSE_CONFIGS: '/ci_prod_purpose_configs',
    GET_CI_PROD_PURPOSE_CONFIG_BY_CI_PRODUCT_ID: '/get_ci_prod_purpose_config_by_ci_product_id',
    CI_PROD_COLLATERALS_CONFIGS: '/ci_prod_collaterals_configs',
    GET_CI_PROD_COLLATERALS_CONFIG_BY_CI_PRODUCT_ID: '/get_ci_prod_collaterals_config_by_ci_product_id',
    CI_OTHER_MORTGAGE_DETAILS: '/ci_other_mortgage_details',
    CI_BONDS_MORTGAGE_DETAILS:'/ci_bonds_mortgage_details',
    CI_PROPERY_MORTGAGE_DETAILS: '/property_mortgages',
    CI_OTHER_LOAN_DETAILS: '/ci_other_loan_details',
    GET_CI_OTHER_LOANS_DETAILS_BY_CI_LOAN_APPLICATION_ID: '/get_ci_other_loans_details_by_ci_loan_application_id',
    CI_MORTGAGE_DETAILS_SUMMARIES: '/ci_mortgage_details_summaries',
    CI_LOAN_VEHICLE_MORTGAGE_DETAILS: '/ci_loan_vehicle_mortgage_details',
    CI_LOAN_OUTSTANDING_DETAILS: '/ci_loan_outstanding_details',
    CI_LOAN_NOTICE_DETAILS: '/ci_loan_notice_details',
    GET_CI_NOTICE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_ci_notice_details_by_loan_application_id',
    CI_LOAN_NOMINEE_DETAILS: '/ci_loan_nominee_details',
    CI_LOAN_GUARDIAN_DETAILS:'/ci_member_guardian_details',
    CI_LOAN_LINKED_SHARECAPITAL_CONFIGS: '/ci_loan_linked_sharecapital_configs',
    GET_CI_LOAN_LINKED_SHARECAPITAL_CONFIG_BY_CI_PRODUCT_ID: '/get_ci_loan_linked_sharecapital_config_by_ci_product_id',
    CI_LOAN_LAND_MORTGAGE_DETAILS: '/ci_loan_land_mortgage_details',
    CI_LOAN_INSURANCE_DETAILS: '/ci_loan_insurance_details',
    CI_LOAN_GUARANTOR_DETAILS: '/ci_loan_guarantor_details',
    CI_LOAN_GOLD_MORTGAGE_DETAILS: '/ci_loan_gold_mortgage_details',
    CI_LOAN_GENEALOGY_TREES: '/ci_loan_genealogy_trees',
    GET_CI_GENEALOGY_TREE_DETAILS_BY_LOAN_APPLICATION_ID: '/get_ci_genealogy_tree_details_by_loan_application_id',
    CI_LOAN_DOCUMENTS_DETAILS: '/ci_loan_documents_details',
    CI_LOAN_DISBURSEMENT_SCHEDULES: '/ci_loan_disbursement_schedules',
    CI_LOAN_DISBURSEMENT:'ci_loan_',
    CI_LOAN_CO_APPLICANT_DETAILS: '/ci_loan_co_applicant_details',
    GET_CI_LOAN_CO_APPLICANT_BY_LOAN_APPLICATION_ID: '/get_ci_loan_co_applicant_by_loan_application_id',
    CI_LOAN_CHARGES_DETAILS: '/ci_loan_charges_details',
    CI_LOAN_APPRAISER_DETAILS: '/ci_loan_appraiser_details',
    CI_LOAN_APPLICATIONS: '/ci_loan_applications',
    CI_LOAN_APPLICATION_APPROVAL :'/ci_loan_application_approval',
    CI_LOAN_KYC_DETAILS:'/ci_loan_kyc_details',
    GET_CI_LOAN_KYC_DETAILS_BY_ADMISSION_NUMBER:'/get_ci_loan_kyc_details_by_admission_number',
    GET_KYC_DETAILS_BY_CI_LOAN_APPLICATION_ID:'/get_ci_loan_kyc_details_by_ci_loan_application_id',
    CI_LOAN_COMMUNICATION :'/ci_loan_communication',
    GET_COMMUNICATIONS_BY_LOAN_APPLICATION_ID:'/get_communications_by_loan_application_id',
    CI_INTEREST_POLICY_CONFIGS: '/ci_interest_policy_configs',
    GET_CI_INTEREST_POLICY_CONFIG_BY_CI_PRODUCT_ID: '/get_ci_interest_policy_config_by_ci_product_id',
    CI_FORECLOSER_DETAILS: '/ci_forecloser_details',
    GET_BY_CI_LOAN_APPLICATION_ID: '/get_by_ci_loan_application_id',
    GET_CI_LOAN_DOCUMENTS_BY_APPLICATION_ID:'/get_ci_loan_documents_by_application_id',
    CI_FIELD_VERIFICATION_DETAILS: '/ci_field_verification_details',
    GET_CI_FIELD_VERIFICATION_DETAILS_BY_LOAN_APPLICATION_ID: '/get_ci_field_verification_details_by_loan_application_id',
    CI_DISBURSEMENTS: '/ci_disbursements',
    CI_DISBURSEMENT_APPROVAL: '/ci_disbursement_approval',
    CI_COLLECTIONS: '/ci_collections',
    CI_CHEQUE_TRANSACTION_DETAILS: '/ci_cheque_transaction_details',
    CI_CHARGES_COLLECTION_DETAILS: '/ci_charges_collection_details',
    CI_CASH_TRANSACTION_DENOMINATIONS: '/ci_cash_transaction_denomination',
    CI_APPORTION_CONFIGS: '/ci_apportion_configs',
    GET_CI_APPORTION_CONFIGS_BY_CI_PRODUCT_ID: '/get_ci_apportion_config_by_ci_product_id',
    CI_ACCOUNT_LEDGER_DETAILS: '/ci_account_ledger_details',
    CI_LOAN_SAVE_GUARANTOR_LIST:'/save_guarantor_list',
    FD_CUMULATIVE_INTEREST_POLICY_CONFIG: '/fd_commulative_interest_policy_config',
    GET_INTERST_POLICY_CONFIG_BY_PRODUCT_ID: '/get_interst_policy_config_by_product_id',
    FD_CUMMULATIVE_ACCOUNT_COMMUNICATION: '/fd_cummulative_account_communication',
    GET_COMMUNICATION_DETAILS_BY_FD_CUMULATIVE_ACCOUNT_ID_AND_COMMUNICATIONTYPE_AND_ADMISSION_NUMBER: '/get_communication_details_by_fd_cummlative_account_id_and_communicationType_and_admission_number',
    GET_COMMUNICATION_DETAILS_BY_FD_CUMULATIVE_ACCOUNT_ID_AND_COMMUNICATIONTYPE: '/get_communication_details_by_fd_cummlative_account_id_and_communicationType',
    GET_COMMUNICATION_BY_FD_CUMMULATIVE_ACCOUNT_ID: '/get_communication_by_fd_cummulative_account_id',
    FD_CUMULATIVE_ACCOUNT_GAURDIAN: '/fd_cummulative_account_gaurdian',
    GET_GAURDIAN_DETAILS_BY_FD_CUMULATIVE_ACCOUNT_ID: '/get_gaurdian_details_by_fd_cummulative_account_id',
    FD_CUMULATIVE_ACCOUNT_KYC: '/fd_cummulative_account_kyc',
    GET_KYC_DETAILS_BY_FD_CUMULATIVE_ACCOUNT_ID_MEMBER_TYPE_AND_ADMISSION_NUMBER: '/get_kyc_details_by_fd_cummulative_account_id_member_type_and_admission_number',
    GET_KYC_DETAILS_BY_FD_CUMULATIVE_ACCOUNT_ID_AND_MEM_TYPE_MEMBER_ID: '/get_kyc_details_by_fd_cummulative_account_id_and_mem_type_member_id',
    GET_KYC_DETAILS_BY_FD_CUMULATIVE_ACCOUNT_ID: '/get_kyc_details_by_fd_cummulative_account_id',
    GET_KYC_DETAILS_BY_ACCOUNT_ID:'/get_kyc_details_by_term_account_id',
    FD_CUMMULATIVE_ACCOUNT_NOMINEE: '/fd_cummulative_account_nominees',
    GET_NOMINEE_BY_FD_CUMULATIVE_ACCOUNT_ID: '/get_nominee_by_fd_cummulative_account_id',
    FD_CUMULATIVE_REQUIRED_DOCUMENTS_CONFIG: '/fd_cummulative_required_documents_config',
    FD_CUMULATIVE_PRODUCT_DEFINITION: '/fd_cummulative_product_definition',
    GET_APPROVED_FD_CUMULATIVE_PRODUCTS: '/get_approved_fd_commulative_products',
    FD_CUMULATIVE_JOINT_ACC_HOLDER_DETAILS: '/fd_cummulative_joint_acc_holder_details',
    FD_CUMMULATIVE_FAS: '/fd_cummulative_fas',
    CASH_COUNTER: '/cash_counter',
    CASTE: '/caste',
    COMMUNITY: '/community',
    VAULT: '/vault',
    MEMBER_TYPE: '/member_types',
    BRANCH_TO_BRANCH_TRANSACTION: '/branch_to_branch_transaction',
    VAULT_TO_COUNTER_TRANSACTION: '/vault_to_counter_transaction',
    VAULT_TO_COUNTER_TRANSACTION_DENOMINATION: '/vault_to_counter_transaction_denomination',
    DENOMINATION: '/denomintaion',
    VAULT_TO_DCCB_TRANSACTION: '/vault_to_dccb_transaction',
    EXCHANGE: '/exchange',
    COUNTER_WISE_DIFFERENCE_AMOUNT_DENOMINATION: '/counter_wise_difference_amount_denomination',
    DAMAGED_OR_FAKE_NOTES: '/damaged_or_fake_notes',
    VAULT_CASH: '/vault_cash',
    //agent_details_transaction
    AGENT_DETAILS:"/agent",
    GET_PREVIEW_DETAILS:"/get_preview_details",
    // BASIC_DETAILS:"/membership_basic_details",
    AGENT_COMMUNICATION:"/agent_communication",
    GET_COMMUNICATION_DETAILS_BY_AGENT_ID:"/get_communication_details_by_agent_id",
    GET_MEMBER_COMMUNICATION_DETAILS_BY_MEMBER_ID_AND_PACS_ID:"/get_member_communication_details_by_memberId_and_pacsId",
    AGENT_KYC_DETAILS:"/agent_kyc_details",
    GET_KYC_DETAILS_BY_AGENT_ID:"/get_kyc_details_by_agent_id",
    AGENT_NOMINEE:"/agent_nominee",
    AGENT_NOMINEE_DETAILS_BY_AGENT_ID:"/get_nominee_details_by_agent_id",
    AGENT_SECURITY:'/agent_security',
    GET_AGENT_SECURITY_DETAILS_BY_AGENT_ID:'/get_agent_security_details_by_agent_id',
    GET_AGENT_SECURITY_CONFIG_BY_SECURITY_CONFIG_ID:'/get_agent_security_config_by_security_config_id',
    AGENT_SURITY_DETAILS:'/agent_surity_details',
    GET_SURITY_DETAILS_BY_AGENT_ID:'/get_surity_details_by_agent_id',
    SAVE_AGENT_SURITY_DETAILS_LIST:'/save_agent_surity_details_list',
    GET_ALL_DEPOSIT_ACCOUNT_MEMBERS:"/get_all_deposit_account_members",
    GET_KYC_DETAILS_BY_ADMISSION_NUMBERS:"/get_kyc_details_by_admission_number",
    LAND_TYPE: '/land_type',
    IRRIGATION_TYPE: '/irrigation_type',
    LAND_OWNERSHIP: '/land_ownership',


    COUNTER_DENOMINATION:'/counter_denomination',
    GET_ALL_TRANSACTIONS_FOR_CASHIER_SCROLL:'/get_all_transactions_for_cashier_scroll',
    BASIC_DETAILS: "/membership_basic_details",
    COMMUNICATION: "/membership_communication",
    SAO_KYC_DETAILS: "/sao_loan_kyc_details",
    COVERED_VILLAGES:"/covered_villages",
    INSURANCE_VENDOR_DETAILS: '/insurance_vendor_details',
    BORROWING_ACCOUNTS:'/borrowing_accounts',
    GET_PREVIEW_DATA_BY_BORROWING_ACCOUNTID:'/get_preview_data_by_borrowing_accountId',
    GET_BORROWING_ACCOUNTS_LIST_BY_PRODUCTID:'/get_borrowing_accounts_list_by_productId',
    GET_BORROWING_ACCOUNTS_LIST_BY_PACSID_AND_BRANCHID:'/get_borrowing_accounts_list_by_pacsId_and_branchId',
    GET_MEMBERSHIP_DETAILS_BY_ADMISSION_NUMBER:'/get_membership_details_by_admission_number',
    GET_MEMBERSHIP_GROUP_DETAILS_BY_ADMISSION_NUMBER:'/get_membership_group_details_by_admission_number',
    GET_MEMBER_DETAILS_BY_APPLICATION_ID:'/get_member_details_by_loan_application_id',

    GET_ACTIVE_PRODUCTS_BASED_ON_PACSID:'/get_all_active_products_based_on_pacsId',
    SAO_LOAN_COMMUNICATION:'/sao_loan_communication',
    GET_SAO_REQUIRED_CONFIG_BY_PRODUCT_ID:'/get_sao_required_documents_config_list_by_product_id',
    GET_COMMUNICATION_DETAILS_BY_LOAN_APPLICATION_ID:'/get_communications_by_loan_application_id',
    GET_BY_LOAN_ID_MEMBER_TYPE_AND_ADMISSION_NUMMBER:'/get_communcation_by_application_id_and_member_type_and_admission_number',
    GET_BY_LOAN_ID_MEMBER_TYPE:'/get_communication_details_by_loan_application_id_and_communicationType',
    SI_BORROWING_ACCOUNTS:'/si_borrowing_accounts',
    GET_SI_BORROWING_ACCOUNTS_LIST_BY_PRODUCTID:'/get_si_borrowing_accounts_list_by_si_productId',
    GET_SI_BORROWING_ACCOUNTS_LIST_BY_PACSID_AND_BRANCHID:'/get_si_borrowing_accounts_list_by_pacsId_and_branchId',
    GET_PREVIEW_DATA_BY_SI_BORROWING_ACCOUNTID :'/get_preview_data_by_si_borrowing_accountId',
    FINANCIAR_BANK_DETAILS:'/financiar_bank_details',
    GET_ALL_ACTIVE_PRODUCTS_BASED_ON_PACSID:'/get_all_active_products_based_on_pacsId',
    GET_ALL_BY_PRODUCTID:'/get_all_by_productId',
    SI_PRODUCTS:'/si_products',
    SI_PRODUCT_PURPOSE_CONFIGS:'/si_product_purpose_configs',
    SI_BORROWING_ACCOUNT_MAPPED_LOANS:'/si_borrowing_account_mapped_loans',
    GET_SI_BORROWING_ACCOUNT_MAPPED_LOANS_LIST_BY_PACSID_AND_BRANCHID:'/get_si_borrowing_account_mapped_loans_list_by_pacsId_and_branchId',
    GET_SI_BORROWING_ACCOUNT_MAPPED_LOANS_LIST_BY_BORROWING_ACCOUNTID:'/get_si_borrowing_account_mapped_loans_list_by_borrowing_accountId',
    SI_BORROWING_ACCOUNT_DOCUMENTS:'/si_borrowing_account_documents',
    GET_BY_SI_BORROWING_ACCOUNT_ID:'/get_by_si_borrowing_account_id',
    CI_BORROWING_ACCOUNTS:'/ci_borrowing_accounts',
    CI_PRODUCTS:'/ci_products',
    CI_PRODUCT_PURPOSE_CONFIGS:'/ci_product_purpose_configs',
    GET_ALL_ACTIVE_PRODUCTS_BASED_ON_PACS_ID:'/get_all_active_products_based_on_pacsId',
    CI_BORROWING_ACCOUNT_MAPPED_LOANS:'/ci_borrowing_account_mapped_loans',
    GET_BORROWING_ACCOUNT_MAPPED_LOANS_LIST_BY_PACSID_AND_BRANCHID:'/get_borrowing_account_mapped_loans_list_by_pacsId_and_branchId',
    GET_BORROWING_ACCOUNT_MAPPED_LOANS_LIST_BY_BORROWING_ACCOUNTID:'/get_borrowing_account_mapped_loans_list_by_borrowing_accountId',
    CI_BORROWING_ACCOUNT_DOCUMENTS:'/ci_borrowing_account_documents',
    GET_BY_BORROWING_ACCOUNT_ID:'/get_by_borrowing_account_id',
    GET_AGENT_ACCOUNT_MAPPING_DETAILS_BY_AGENT_ID:'/get_agent_account_mapping_details_by_agent_id',
    SAO_BORROWING_ACCOUNTS:'/sao_borrowing_accounts',
    SAO_PRODUCTS:'/sao_products',
    SAO_PRODUCT_PURPOSE_CONFIGS:'/sao_product_purpose_configs',
    SAO_BORROWING_ACCOUNT_MAPPED_LOANS:'/sao_borrowing_account_mapped_loans',
    SAO_BORROWING_ACCOUNT_DOCUMENTS:'/sao_borrowing_account_documents',
    SAVE_GURANTOR_LIST:'/save_sao_loan_guarantor_details_list',
    GET_GURANTOR_DETAILS_BY_APP_ID:'/get_guarantor_details_by_loan_application_id',

    AGENT_ACCOUNT_MAPPING:'/agent_account_mapping',
    SAVE_AGENT_ACCOUNT_MAPPING_DETAILS_LIST:'/save_agent_account_mapping_details_list',
    TERM_BORROWING_ACCOUNTS:'/term_borrowing_accounts',
    PRODUCTS:'/products',
    PRODUCT_PURPOSE_CONFIGS:'/product_purpose_configs',
    BORROWING_ACCOUNT_MAPPED_LOANS:'/borrowing_account_mapped_loans',
    BORROWING_ACCOUNT_DOCUMENTS:'/borrowing_account_documents',
    LOAN_PURPOSES:'/loan_purposes',
    CROP_TYPES:'/crop',
    SOIL_TYPES:'/soil_types',
    SUB_PRODUCT:'/sub_products',
    GET_SAO_KYC_DETAILS_BY_ADMISSION_NUMBER_AND_MEMBER_TYPE:'/get_kyc_details_by_loan_application_id',
    KYC_DOC_TYPE:'/kyc_document_types',
    DOCUMENT_TYPES:'/document_types',
    SI_BORROWING_DISBURSMENT:'/si_borrowing_disbursment',
    GET_BY_PACSID_AND_BRANCHID:'/get_by_pacsid_and_branchid',
    GET_MEMBER_DETAILS_BY_ADMISSION_NUMBER:'/get_by_admission_number',
    GET_DISBURSHMENT_LIST_APPLICATION_ID:'/get_sao_disbursement_list_by_application_id',
    GET_MEMBERSHIP_BASIC_DETAILS_BY_ADMISSION_NO:'/get_member_ship_basic_details_by_admissionNumber',

    //Investments
    TERM_DEPOSIT_INVESTMENT_ACCOUNTS:'/term_deposit_investment_accounts',
    TERM_DEPOSIT_INVESTMENT_ACCOUNT_STATUS:'/term_deposit_investment_account_status',
    GET_PREVIEW_BY_TERM_ACCOUNT_ID:'/get_preview_by_termAccountId',
    GET_BY_PRODUCT_ID:'/getByProductId',
    GET_BY_PAC_ID_AND_BRANCH_ID:'/getByPacIdAndBranchId',
    INVESTMENT_ACCOUNT_DOCUMENTS:'/investment_account_documents',
    GET_ALL_BY_TERM_ACCOUNT_ID:'/get_all_by_termAccountId',
    GET_ALL_BY_PRODUCT_ID:'/get_all_by_productId',
    SHARES_INVESTMENT_ACCOUNTS:'/shares_investment_accounts',
    GET_ALL_SHARE_INVESTMENT_ACCOUNTS_BY_PAC_ID_AND_BRANCH_ID:'/get_all_sharesInvestmentAccounts_by_pacsId_and_branchId',
    SHARES_INVESTMENT_ACCOUNT_STATUS_APPROVAL:'/shares_investment_account_status_approval',
    GET_PRODUCT_ASSOCIATED_BANK_NAME:'/get_product_associated_bank_name',
    DEPOSIT_INVESTMENT_FILLED_COPY_DOWNLOAD:'/term_deposit_investment_preview_download',
    SHARES_INVESTMENT_FILLED_COPY_DOWNLOAD:'/shares_investment_preview_download',
    INVESTMENT_INTEREST_PAYMENT:'/interest_payments',
    INTEREST_PAYMENT_BY_INVESTMENT_ID:'/get_interest_payments_list_by_term_acc_id',

    // membership
    GET_MEMBER_BY_ADMISSION_NUMBER : "/get_membership_details_by_admission_number",
    GET_INSTITUTION_BY_ADMISSION_NUMBER : "/get_mem_institutions_by_admission_number",
    GET_GROUP_BY_ADMISSION_NUMBER : "/get_membership_group_details_by_admission_number",
    GET_NOMINEE_BY_ADMISSION_NUMBER : "/get_member_nominee_details_by_admission_number",
    GET_GUARDAIN_BY_ADMISSION_NUMBER :"/get_member_guardian_details_by_admission_number",
    GET_KYC_BY_ADMISSIONnuMBER : "/get_all_sb_acc_kyc_details_by_admission_number",
    GET_KYC_BY_ADMISSIONUMBER : "/get_all_fd_acc_kyc_details_by_admission_number",
    DUPLICATE_CHECK_FOR_KHATA_NUMBER :'/duplicate_check_for_khata_number',



    GET_KYC_BY_ADMISSION_NUMBER :"/get_all_fd_acc_kyc_details_by_admission_number",

    SB_KYC :'/sb_acc_kyc_details',
    GET_SI_LOAN_KYC_DETAILS_BY_ADMISSION_NUMBER : "/get_all_si_loan_kyc_details_by_admission_number",
    SI_LOAN_KYC_DETAILS: "/si_loan_kyc_details",
    GET_SI_LOAN_KYC_DETAILS_BY_LOAN_ACC_ID: "/get_loan_application_details_by_loan_application_id",
    SI_LOAN_GUARDIAN_DETAILS: '/si_member_guardian_details',
    GET_SI_LOAN_GURADIAN_DETAILS_BY_LOAN_ACC_ID: 'get_si_loan_guardian_details_by_loan_acc_id',
   
    GET_ALL_DISBURSEMENT_PENDING_LOANS:'/get_all_disbursement_pending_loans',
    ADD_BORROWING_MAPPING_LIST:'/add_borrowings_mapping_list',
    submit_for_approval: '/submit_for_approval',
    MEMBERSHIP_PDF_DOWNLOAD : "/membership_preview_download",
    MEMBERSHIP_GROUP_PDF_DOWNLOAD : "/group_preview_download",
    MEMBERSHIP_INSTITUTION_PDF_DOWNLOAD:"/institution_preview_download",
    REQUIRED_DOCUMENT_DETAILS:"/required_document_details",
    GET_REQUIRED_DOCUMENTS_BY_MEMBERID_AND_MEMBER_TYPE: '/get_required_document_details_by_member_id',





    //Demand deposits
    GET_ACTIVE_PRODUCT_DEFINITION_BY_PACS_ID : '/get_all_active_product_based_on_pacs_id',
    CI_LOAN_APPLICATION:'/ci_loan_applications',
    TERM_LOAN_APPLICATION:'/term_loan_applications',
    TERM_BORROWING_ACCOUNT_MAPPED_LOANS:'/term_borrowing_account_mapped_loans',
    TERM_BORROWING_ACCOUNT_DOCUMENTS:'/term_borrowing_account_documents',
    TERM_PRODUCTS:'/term_products',
    TERM_PRODUCT_PURPOSE_CONFIGS:'/term_product_purpose_configs',

    SB_TRANSACTION :"/sb_transaction_details",
    GET_TOP_FIVE_RECORDS_OF_TRANSACTIONS:"/get_latest_five_transaction_details_by_sb_acc_id",
    SAVE_JOINT_HOLDER_LIST : "/save_joint_holder_list",
    REQUIRED_DOCUMENTS : "/required_document_details",
    REQUIRED_DOCUMENTS_BY_SB_ACC_ID:"/get_required_document_details_by_sb_acc_id",
    GET_REQUIRED_DOCUMENTS_BY_ADMISSION_NUMBER : "/get_all_required_document_details_by_admission_number",
  

    GET_PRODUCT_LIST_BY_PACSID:'/get_product_list_by_pacsId',
    GET_ALL_ACTIVE_PRODUCT_BASED_ON_PACS_ID:'/get_all_active_product_based_on_pacs_id',
    GET_ACTIVE_PRODUCT_BASED_ON_PRODUCT_ID:'/get_active_product_based_on_product_id',
    REQUIRED_DOCUMENTS_CONFIG:'/required_documents_config',
    GER_REQUIRED_DOCUMENTS_CONFIG_BY_PRODUCT_ID:'/get_requried_documents_config_by_product_id',
    RD_REQUIRED_DOCUMENT_DETAILS:'/rd_required_document_details',
    GET_REQUIRED_DOCUMENT_DETAILS_BY_ACC_ID:'/get_required_document_details_by_acc_id',
    

    SB_SERVICE_CHARGES_CONFIGURATION : "/account_service_config_charges",  
    GET_SB_SERVICE_CHARGES_CONFIG_DETAILS_BY_PRODUCT_ID : "/get_account_service_config_Charges_by_product_id",

    STANDAERED_INSTRUCTION : "/sb_standing_instructions",
    GET_ALL_STANDAERED_INSTRUCTIONS_BY_ACCOUNT_NUMBER:"/get_all_by_account_number",

    AMOUNT_BLOCK : "/sb_amount_blocking_details",
    GET_ALL_AMOUNT_BLOCK_BY_ACCOUNT_NUMBER : "/get_all_blocked_amounts_by_account_number",
    SAVINGS_ACCOUNT_PDF_DOWNLOAD : "/savings_application_preview_download",
    SB_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/product_definition_preview_download',

   //  closure of Sb 
   RD_ACCOUNT_DETAILS_ACCOUNT_NUMBER :'/get_rd_application_by_account_number',
   TERM_ACCOUNT_DETAILS_ACCOUNT_NUMBER :'/get_term_application_by_account_number',
  



    // FD_NON_CUMMULATIVE 
    FD_NON_CUMMULATIVE_ACCOUNT:'/fd_non_cummulative_accounts',
    FD_NON_CUMM_PRODUCT_DEFINITION:'/fd_non_cummulative_product_definition',
    GET_APPROVED_PRODUCT_DEFINITION:'/get_approved_fd_non_commulative_products',
    PRODUCT_DEFINITION_PREVIEW:'/get_product_overview_by_id',
    FD_NON_CUMM_COMMUNICATION_DETAILS:'/fd_non_cummulative_account_communication',
    FD_NON_CUMULATIVE_NOMINEE_DETAILS:'/fd_non_cummulative_account_nominees',
    FD_NON_CUMULATIVE_GUARDAIN_DETAILS:'/fd_non_cummulative_account_guardian',
    FD_NON_CUMULATIVE_KYC_DETAILS:'/fd_non_cummulative_account_kyc',
    ADD_FD_NON_CUMMULATIVE_WITH_MEMBER_MODULE :'/add_fd_non_cummulative_with_membership_module_details',
    UPDATE_FD_NON_CUMMULATIVE_ACCOUNT_WITH_MEMBER_MODULE:'/update_fd_non_cummulative_with_membership_module_details',
     UPDATE_FD_CUMMULATIVE_ACCOUNT_WITH_MEMBER_MODULE:'/update_fd_cummulative_with_membership_module_details',
    ADD_CUMMULATIVE_WITH_MEMBER_MODULE :'/add_fd_cummulative_with_membership_module_details',
    FD_NON_CUMULATIVE_JOINT_DETAILS:'/fd_non_cummulative_joint_acc_holder_details',
    SAVE_LIST_FD_NON_CUMULATIVE_JOINT_DETAILS:'/save_joint_holder_list',
    UPDATE_RD_ACCOUNT_WITH_MEMBER_MODULE:'/update_rd_accounts_with_membership_module_details',
    ADD_RD_ACCOUNT_WITH_MEMBER_MODULE:'/add_rd_accounts_with_membership_module_details',

    SI_LOAN_NOMINEE_DETAILS_BY_ACCOUNT_ID: '/get_si_loan_nominee_details_by_application_id',
    SI_LOAN_GUARANTOR_DETAILS_BY_ACCOUNT_ID: '/get_si_loan_gurantor_details_by_application_id',

    SI_GOLD_LOAN_MORTGAGE_DETAILS_BY_ACCOUNT_ID: '/get_si_gold_loan_mortgage_details_by_application_id',
    SI_LAND_LOAN_MORTGAGE_DETAILS_BY_ACCOUNT_ID: '/get_si_land_loan_mortgage_details_by_application_id',
    SI_BOND_LOAN_MORTGAGE_DETAILS_BY_ACCOUNT_ID: '/get_si_bond_loan_mortgage_details_by_application_id',
    SI_VEHICLE_LOAN_MORTGAGE_DETAILS_BY_ACCOUNT_ID: '/get_si_vehicle_loan_mortgage_details_by_application_id',
    SI_STORAGE_LOAN_MORTGAGE_DETAILS_BY_ACCOUNT_ID: '/get_si_storage_loan_mortgage_details_by_application_id',
    SI_OTHER_LOAN_MORTGAGE_DETAILS_BY_ACCOUNT_ID: '/get_si_other_loan_mortgage_details_by_application_id',

    SI_LOAN_DOCUMENT_DETAILS_BY_ACCOUNT_ID: '/get_si_loan_document_details_by_application_id',
    SI_LOAN_GENEALOGY_DETAILS_BY_ACCOUNT_ID: '/get_si_loan_genealogy_details_by_application_id',
    SI_LOAN_PREVIEW_DETAILS: '/get_si_loan_preview_details',
    GET_SI_LOAN_KYC_DETAILS_BY_LOAN_ID: '/get_si_loan_kyc_details_by_application_id',

    GET_SI_LOAN_DOCUMENT_DETAILS_BY_LOAN_ID: '/get_si_documents_details_by_application_id',
    SI_LOAN__ACC_GUARDIAN_GET_BY_ACCOUNT_NUMBER:'/get_guardian_details_by_account_number',
    SAVE_GUARANTOR_DETAILS_LIST : "/save_si_loan_guarantor_details_list",

   FD_NON_CUMULATIVE_PRODUCT_DEFINITION:'/fd_non_cummulative_product_definition',
   GET_BY_PRODUCTID:"/get_by_productId",
   FD_NON_CUMULATIVE_INTEREST_POLICY_CONFIG:"/fd_non_cummulative_interest_policy_config",
   FD_NON_CUMULATIVE_REQUIRED_DOCUMENTS_CONFIG:"/fd_non_cummulative_required_documents_config",
   GET_BY_RD_PRODUCT_ID:"/get_by_rd_product_id",
   RD_PENALITY_CONFIGS:"/rd_penalty_configs",
   RD_REQUIRED_DOCUMENTS_CONFIG:"/rd_required_documents_config",
   FD_NON_CUMMULATIVE_REQUIRED_DOCUMENT_DETAILS:'/fd_non_cummulative_required_document_details',
   GET_ALL_FD_TRANSDACTIONS:"/get_by_term_account_id",
   GET_ALL_FD_NON_CUMMULATIVE_TANSACTIONS:"/get_by_term_account_id",
   GET_ALL_RD_TANSACTIONS:"/get_by_term_account_id",


    // FD_CUMMULATIVE 
    FD_CUMM_COMMUNICATION_DETAILS:'/fd_cummulative_account_communication',
    FD_CUMULATIVE_NOMINEE_DETAILS:'/fd_cummulative_account_nominees',
    FD_CUMULATIVE_GUARDAIN_DETAILS:'/fd_cummulative_account_gaurdian',
    FD_CUMULATIVE_KYC_DETAILS:'/fd_cummulative_account_kyc',
    FD_CUMM_PRODUCT_DEFINITION:'/fd_cummulative_product_definition',
    GET_ALL_ACTIVE_PRODUCTS:'/get_all_active_products',
    GET_JOINT_HOLDER_DETAILS_BY_FD_CIMMULATIVE_ACC_ID:'/get_joint_holder_details_by_fd_cummulative_acc_id',
    FD_CUMMULATIVE_REQUIRED_DOCUMENT_DETAILS: '/fd_cummulative_required_document_details',
    GET_REQUIRED_DOCUMENT_DETAILS_BY_ACCOUNT_ID:'/get_required_document_details_by_account_id',

   GET_INTEREST_POLICY_CONFIG_BY_PRODUCTID:'/get_interest_policy_config_by_product_id',
   GET_SAO_LOAN_LINKED_SHARE_CAPITAL_CONFIG_BY_PRODUCT_ID:'/get_sao_loan_linked_share_capital_config_by_product_id',
   SAO_GET_BY_PRODUCT_ID:'/get_by_product_id',
   GET_INTEREST_POLICY_CONFIG_LIST_BY_PRODUCT_ID:'/get_interest_policy_config_list_by_product_id',
   GET_LOAN_LINKED_SHARE_CAPITAL_LIST_BY_PRODUCT_ID:'/get_loan_linked_share_capital_list_by_product_id',
   GET_TERM_PRODUCT_CHARGES_LIST_BY_PRODUCT_ID:'/get_term_product_charges_list_by_product_id',
   GET_PROD_PURPOSE_CONFIG_LIST_BY_PRODUCT_ID:'/get_prod_purpose_config_list_by_product_id',
   GET_REQUIRED_DOCUMENTS_CONFIG_LIST_BY_PRODUCT_ID:'/get_required_documents_config_list_by_product_id',
   PRODUCT_REQUIRED_DOCUMENTS_CONFIG_GET_BY_PRODUCTID:'/product_required_documents_config_get_by_productId',
   GET_KYC_DETAILS_BY_FD_CUMMULATIVE_ACCOUNT_ID:'/get_kyc_details_by_fd_cummulative_account_id',
   GET_FD_CUMMULATIVE_APPLICATION_BY_ADDMISSION_NUMBER:'/get_fd_cummulative_application_by_admission_number',
   GET_FD_NON_CUMMULATIVE_APPLICATION_BY_ADDMISSION_NUMBER:'/get_fd_non_cummulative_application_by_admission_number',
   GET_RD_APPLICATION_BY_ADDMISSION_NUMBER:'/get_rd_application_by_admission_number',
   FD_TRANSACTION :"/fd_cummulative_accounts_transactions",
   GET_SAO_PROD_PURPOSE_BY_PRODUCT_ID:'/get_sao_product_purpose_config_list_by_product_id',


//Borrowing Product Definition

   SAO_PRODUCT_APPORTION_ORDER:'/sao_product_apportion_configs',
   GET_PRODUCT_APPORTION_CONFIG_LIST_BY_PRODUCTID:'/get_product_apportion_config_list_by_productId',
   SAO_BORROWING_LINKED_SHARECAPITAL_CONFIG:'/sao_borrowing_linked_sharecapital_config',
   BORROWING_LINLED_SHARECAPITAL_CONFIG_GET_BY_PRODUCT_ID:'/borrowing_linked_sharecapital_config_get_by_productId',
   SAO_PRODUCT_CHARGES_CONFIGS:'/sao_product_charges_configs',
   GET_PRODUCT_CHARGES_CONFIG_LIST_BY_PRODUCT_ID:'/get_product_charges_config_list_by_productId',
   SAO_PRODUCT_REQUIRED_DOCUMENTS_CONFIG:'/sao_product_required_documents_config',
   SI_PRODUCT_APPORTION_CONFIGS:'/si_product_apportion_configs',
   GET_PREVIEW_BY_SI_PRODUCTID:'/get_preview_by_si_productId',
   GET_SI_PRODUCT_APPORTION_CONFIG_LIST_BY_SI_PRODUCTID:'/get_si_product_apportion_config_list_by_si_productId',
   SI_BORROWING_LINKED_SHARECAPITAL_CONFIG:'/si_borrowing_linked_sharecapital_config',
  SI_BORROWING_LINKED_SHARECAPITAL_CONFIG_GET_BY_SI_PRODUCTID :'/si_borrowing_linked_sharecapital_config_get_by_si_productId',
  SI_PRODUCT_CHARGES_CONFIGS:'/si_product_charges_configs',
  GET_SI_PRODUCT_CHARGES_CONFIG_LIST_BY_SI_PRODUCTID:'/get_si_product_charges_config_list_by_si_productId',
  SI_PRODUCT_REQUIRED_DOCUMENTS_CONFIG:'/si_product_required_documents_config',
  SI_PRODUCT_REQUIRED_DOCUMENTS_CONFIG_GET_BY_SI_PRODUCTID:'/si_product_required_documents_config_get_by_si_productId',
  CI_PRODUCT_APPORTION_CONFIGS:'/ci_product_apportion_configs',
  CI_BORROWING_LINKED_SHARECAPITAL_CONFIG:'/ci_borrowing_linked_sharecapital_config',
  BORROWING_LINKED_SHARECAPITAL_CONFIG_GET_BY_PRODUCT_ID:'/borrowing_linked_sharecapital_config_get_by_productId',
  CI_PRODUCT_REQUIRED_DOCUMENTS_CONFIG:'/ci_product_required_documents_config',
  TERM_PRODUCT_APPORTION_CONFIGS:'/term_product_apportion_configs',
  TERM_BORROWING_LINKED_SHARECPITAL_CONFIG:'/term_borrowing_linked_sharecapital_config',
  TERM_PRODUCT_REQUIRED_DOCUMENTS_CONFIGS:'/term_product_required_documents_configs',
  TERM_PRODUCT_REQUIRED_DOCUMENTS_CONFIG_GET_BY_PRODUCTID:'/term_product_required_documents_config_get_by_productId',
  



   //Investements Product Definition
   INVESTMENTS_PRODUCTS:'/products',
   UPDATE_PRODUCT_STATUS:'/update_product_status',
   GET_PREVIEW_BY_PRODUCT_ID:'/get_preview_by_productId',
   PRODUCT_ASSOCIATED_BANK_DETAILS:'/product_associated_bank_details',
   PRODUCT_ASSOCIATED_BANK_DETAILS_BY_PRODUCT_ID:'/product_associated_bank_details_by_product_id',
   INTEREST_POLICY_CONFIGS:'/interest_policy_configs',
   INVESTMENT_REQUIRED_DOCUMENTS:'/required_documents',
   GET_BY_PRODUC_ID:'/get_by_produc_id',
   GET_BY_PRODUCT_ID_AND_DOCUMENT_TYPE_ID:'/get_by_product_id_and_document_type_id',
   GET_INVESTED_BANK_DETAILS_BY_PRODUCT_ID:'/investments_bank_details_by_product_id',
  
   GET_SI_LOAN_COLLECTIONS_BY_APPLICATION: '/get_si_loan_collections_by_application_id',
   PRODUCT_PENALITY_CONFIG: '/product_penalty_config',
   GET_GAURDIAN_DETAILS_BY_ACCOUNT_NUMBER:'/get_gaurdian_details_by_account_number',

   GET_TERM_LOAN_APPLICATIONS_BY_PACSID_AND_BRANCHID:'/get_term_loan_applications_by_pacs_id_and_branch_id',
   GET_ALL_SI_LOAN_ACCOUNT_DETAILS_BY_PACS_ID_AND_BRANCH_ID: '/get_si_loan_applications_by_pacs_id_and_branch_id',
   TERM_LOAN_COMMUNICATION:'/term_loan_communication',
   GET_COMMUNICATION_BY_APPLICATION_ID_AND_MEMBER_TYPE_AND_MEMBER_ID:'/get_communcation_by_application_id_and_member_type_and_member_id',
   GET_TERM_LOAN_NOMINEE_DETAILS_BY_APPLICATION_ID:'/get_term_loan_nominee_details_by_application_id',
   TERM_MEMBER_GUARDIAN_DETAILS:'/term_member_guardian_details',
   SAVE_TERM_LOAN_GUARANTOR_DETAILS_LIST:'/save_term_loan_guarantor_details_list',
   GET_GOLD_MORTGAGE_DETAILS_BY_TERM_LOAN_APPLICATION_ID:'/get_gold_mortgage_details_by_term_loan_application_id',
   GET_DETAILS_BY_TERM_LOAN_APPLICATION_ID:'/get_details_by_term_loan_application_id',
   TERM_LOAN_KYC_DETAILS:'/term_loan_kyc_details',
   GET_TERM_DOCUMENTS_DETAILS_BY_APPLICATION_ID:'/get_term_documents_details_by_application_id',
   GET_PRODUCT_DETAILS_BY_PRODUCT_ID_AND_APPLICATION_DATE: '/get_product_details_by_product_id_application_date',
   GET_SI_LOAN_DISBURSEMENT_DETAILS_BY_APPLICATION_ID: '/get_si_loan_disbursement_details_by_application_id',
   GET_MEMBER_GUARDIAN_DETAILS_BY_TERM_LOAN_APPLICATION_ID:'/get_guardian_details_by_term_loan_application_id',
   GET_TERM_LOAN_KYC_DETAILS_BY_APPLICATION_ID:'/get_term_loan_kyc_details_by_application_id',
   GET_ALL_APPROVED_PRODUCTS: '/get_all_approved_products',
   GET_PRODUCT_DETAILS_BY_PRODUCT_ID_APPLICATION_DATE:'/get_product_details_by_product_id_application_date',
   GET_PRODUCT_DETAILS_BY_PRODUCTID_APPLICATION_DATE:'/get_product_details_by_product_id_application_date',
   FD_NON_CUMMULATIVE_APPLICATION_PREVIEW_DOWNLOAD:'/fd_non_cummulative_application_preview_download',
   FD_CUMMULATIVE_APPLICATION_PREVIEW_DOWNLOAD:'/fd_cummulative_application_preview_download',
   RD_APPLICATION_PREVIEW_DOWNLOAD:'/rd_application_preview_download',
   SI_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/si_loan_product_definition_preview_download',
   CI_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/ci_loan_product_definition_preview_download',
   SAO_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/sao_loan_product_definition_preview_download',
   TERM_LOAN_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/term_loan_product_definition_preview_download',


   //Daily Deposits
   ACCOUNTS:'/accounts',
   ACCOUNT_COMMUNICATION:'/account_communication',
   GET_ACCOUNTS_DETAILS_BY_PACSID_AND_BRANCHID:'/get_accounts_by_pacsid_and_branchid',
   ADD_DAILY_DEPOSITS_ACCOUNT_WITH_MEMBER_MODULE:'/add_accounts_with_membership_module_details',
   ACCOUNT_GUARDIAN:'/account_guardian',
   JOINT_ACC_HOLDER_DETAILS:'/joint_acc_holder_details',
   ACCOUNT_NOMINEE:'/account_nominees',
   ACCOUNT_KYC:'/account_kyc',
   GET_ALL_KYC_DETAILS_BY_ADMISSION_NUMBER:'get_all_acc_kyc_details_by_admission_number',
   GET_DAILY_DEPOSITS_KYC_DETAILS_BY_ACCOUNT_ID:'get_kyc_details_by_account_id',
   UPDATE_DAILY_DEPOSITS_ACCOUNT_WITH_MEMBER_MODULE:'/update_account_with_membership_module_details',
   ACCOUNT_REQURIED_DOCUMNETS:'/required_document_details',
   DAILY_DEPOSITS_APPLICATION_PREVIEW_DOWNLOAD:'/daily_deposits_application_preview_download',
   DAILY_DEPOSITS_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/daily_deposits_product_definition_preview_download',
   DAILY_DEPOSIT_TRANSACTION :"/accounts_transactions",
   GET_TOP_FIVE_DAILY_DEPOSITS_RECORDS_OF_TRANSACTIONS:"/get_latest_five_transaction_details_by_acc_id",

   GET_DAILY_DEPOSITS_BY_ADDMISSION_NUMBER:'/get_daily_deposits_by_admission_number',
   //ci Loan
   CI_LOAN_APPLICATION_PREVIEW_DOWNLOAD :'/ci_loan_application_preview_download',
   SI_BORROWING_APPLICATION_PREVIEW_DOWNLOAD:'/si_borrowing_application_preview_download',
   CI_BORROWING_APPLICATION_PREVIEW_DOWNLOAD:'/ci_borrowing_application_preview_download',
   SAO_BORROWING_APPLICATION_PREVIEW_DOWNLOAD:'/sao_borrowing_application_preview_download',
   TERM_BORROWING_APPLICATION_PREVIEW_DOWNLOAD:'/term_borrowing_application_preview_download',
   GET_MEASURING_UNIT:'/get_measuring_unit',
   CUSTOMER_LAND_SURVEY_DETAILS:'/customer_land_survey_details',
   GET_LAND_DETAILS_BY_PASSBOOK_NUMBER:'/get_land_survey_details_by_passbook_number',
   JOINT_HOLDER_SAVE_LIST:'/joint_acc_holder_save_list',
   SI_LOAN_VEHICLE_MORTGAGE_DETAILS:'/si_loan_vehicle_mortgage_details',
   SI_OTHER_MORTGAGE_DETAILS:'/si_other_mortgage_details',
   SI_PROPERY_MORTGAGE_DETAILS:'/si_property_mortgages',
   TERM_PROPERTY_MORTGAGES:'/term_property_mortgages',
   GET_CI_DISBURSEMENT_BY_CI_APPLICATION_ID:'/get_ci_disbursement_list_by_application_id',
   GET_SI_LOAN_APPLICATION_BY_ADDMISSION_NUMBER:'/get_si_loan_application_by_admission_number',
   GET_SAO_LOAN_APPLICATION_BY_ADDMISSION_NUMBER:'/get_sao_loan_application_by_admission_number',
   GET_CI_LOAN_APPLICATION_BY_ADDMISSION_NUMBER:'/get_ci_loan_application_by_admission_number',
   GET_TERM_LOAN_APPLICATION_BY_ADDMISSION_NUMBER:'/get_term_loan_application_by_admission_number',
   GET_AGENT_DETAILS_BY_ADDMISSION_NUMBER:'/get_agent_details_by_admission_number',
   GET_TERM_LOAN_DISBURSEMENT_SCHEDULE_BY_LOAN_APPLICATION_ID:'/get_term_loan_disbursement_schedule_by_loan_application_id',
   GET_TERM_DISBURSEMENT_LIST_BY_APPLICATION_ID:'/get_disbursement_list_by_application_id',
   GET_TERM_LOAN_COLLECTION_BY_APPLICATION_ID:'/get_term_loan_collections_by_application_id',


   FD_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/fd_cummulative_product_definition_preview_download',
   FD_NON_CUMM_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/fd_non_cummulative_product_definition_preview_download',
   RD_PRODUCT_DEFINITION_PREVIEW_DOWNLOAD:'/rd_product_definition_preview_download',

   FD_CUMMULATIVE_ACCOUNTS_TRANSACTIONS:'/fd_cummulative_accounts_transactions',
   GET_ALL_AGENT_TRANSACTION_BY_AGENT_ID:'/get_agent_transaction_by_agent_id' ,
   GET_DAILY_DEPOSIT_TRANSCATION_BY_ACCOUNT_ID:'/get_latest_five_transaction_details_by_acc_id',
   SI_LOAN_APPLICATION_PREVIEW_DOWNLOAD :'/si_loan_application_preview_download',
   TERM_LOAN_FIELD_VISIT_CONFIG:'/term_loan_field_visit_config',
   GET_TERM_LOAN_FIELD_VISIT_LIST_BY_PRODUCT_ID:'/get_term_loan_field_visit_list_by_product_id',
   GET_TERM_LOAN_DISBURSEMENT_SCHEDULE_LIST_BY_PRODUCT_ID:'/get_term_loan_disbursement_schedule_list_by_product_id'

}