export const SavingsBankConfigConstants = {

  COMMON_CATEGORY: "/menu/configurations/savings_bank_config/common_category",
  ADD_COMMON_CATEGORY: "/menu/configurations/savings_bank_config/add_common_category",
  DEBIT_CARD_TYPES: "/menu/configurations/savings_bank_config/debit_card_types",
  ADD_DEBIT_CARD_TYPE: "/menu/configurations/savings_bank_config/add_debit_card_type",
  WORK_FLOW: "/menu/configurations/savings_bank_config/workflow",
  ADD_WORK_FLOW: "/menu/configurations/savings_bank_config/add_workflow",
  PRODUCT_TYPES: "/menu/configurations/savings_bank_config/product_types",
  ADD_PRODUCT_TYPE: "/menu/configurations/savings_bank_config/add_product_type",
  SETTINGS: "/menu/configurations/savings_bank_config/settings",
  ADD_SETTING: "/menu/configurations/savings_bank_config/add_setting",
  FORM_TYPES: "/menu/configurations/savings_bank_config/form_types",
  ADD_FORM_TYPE: "/menu/configurations/savings_bank_config/add_form_types",
  DOCUMENT_TYPES: "/menu/configurations/savings_bank_config/document_types",
  ADD_DOCUMENT_TYPE: "/menu/configurations/savings_bank_config/add_document_type",
  VOTER_CONFIG: "/menu/configurations/savings_bank_config/voter_config",
  ADD_VOTER_CONFIG: "/menu/configurations/savings_bank_config/add_voter_config",
  SERVICE_TYPES: "/menu/configurations/savings_bank_config/service_types",
  ADD_SERVICE_TYPE: "/menu/configurations/savings_bank_config/add_service_type",
}