import { environment } from "src/environments/environment";

export const Configuration = {
    
    COMMON_MASTER:environment.commonmaster,
    MEMBERSHIP:environment.membership,
    DEMANDDEPOSITS: environment.demanddeposits,
    TERMDEPOSITS:environment.termdeposits,
    LOANS:environment.loans,
    DAILYDEPOSITS:environment.dailydeposits,
    BORROWINGS:environment.borrowings,
    CASHCOUNTER:environment.cashcounter,
    AGENTDETAILS:environment.agentmanagement,
    RBAC:environment.rbac,
    INVESTMENTS:environment.investments,
    LOCKERS:environment.lockers,
    
    ADD: '/add',
    UPDATE: '/update',
    GET : '/get',
    GET_ALL : '/get_all',
    DELETE : '/remove',

    STATE: '/states',
    GET_STATE_BY_COUNTRY_ID:'/get_state_by_country_id',
    DISTRICT:'/district',
    COUNTRY:'/country',
    GET_DISTRICT_BY_STATE_ID:'/get_district_by_state_id',
    SUB_DISTRICT:'/sub_district',
    GET_SUB_DISTRICTS_BY_DISTRICT_ID:'/get_sub_districts_by_district_id',
    VILLAGES:'/villages',
    GET_VILLAGES_BY_SUB_DISTRICT_ID:'/get_villages_by_sub_district_id',
    COMMUNITY :'/community',
    CASTE:'/caste',
    RELATIONSHIP_TYPES:'/relationship_types',
    OCCUPATION_TYPES:'/occupation_types',
    MARITAL_STATUS_TYPES:'/marital_status_types',
    QUALIFICATION:'/qualification',
    FARMER_TYPES:'/farmer_types',
    PRODUCT_FEE_RULES:'/product_fee_rules',
    PRODUCT_TYPE_RULES:'/product_type_rules',
    SERVICE_TYPES:'/service_types',
    REASON:'/reason',
    TRANSACTION_MODES:'/transaction_modes',
    ACCOUNTS_TYPES:'/accounts_types',
    DOC_TYPES:'/document_types',
    PACS_DETAILS:'/pacs_details',
    SOCIETY_BRANCHES:'/society_branches',
    PRODUCTS:'/products',
    DENOMINATION_TYPE:'/denomintaion_types',
    DCCB:'/dccb',
    DCCB_BRANCH:'/dccb_branch',
    DESIGNATION_TYPES:'/designation_types',
    APPORTION_TYPES:'/apportion_types',
    DIVISION:'/division',
    BLOCKS:'/blocks',
    KYC_DOC_TYPES:'/kyc_document_types',
    VOTERS_CONFIG:'/voter_config',
    TD_FORM_TYPES:'/td_form_types',
    LAND_TYPES:'/land_type',
    LAND_OWNERSHIP_TYPE:'/land_ownership',
    GOLD_RATES:'/gold_rates',
   

    // SB Config
    COMMON_CATEGORY:'/common_categories',
    COMMON_STATUS:'/common_status',
    COMMON_STATUS_BY_CATEGORY : '/get_status_by_category',
    GET_ALL_CATEGORY_WITH_CATEGORY_STATUS:'/get_all_category_with_category_status',
    COMMON_STATUS_LIST_BY_CATEGORY:'/get_all_common_status_by_category_id',
    DEBIT_CARD_TYPES:'/debit_card_types',
    DENOMINATION_TYPES:'/denomintaion_types',
    WORK_FLOW:'/work_flow',
    WORK_FLOW_STEPS:'/work_flow_steps',
    GET_WORK_STEPS_BY_ID_AND_CATEGORY: '/get_all_workflow_steps ',
    SB_FORM_TYPES:'/sb_form_types',
    DESTINATION_ACCOUNT_TYPES : '/accounts_types',
    PRODUCT_DEFINITION : '/product_definition',
    PRODUCT_TYPES : '/product_types',
    MODE_OF_OPERATIONS: '/operation_types',
    ORG_HEIRARCHY : '/org_heirarchy',
    SAVING_ACCOUNT : '/savings_account',
    MEMBERSHIP_BASIC_DETAILS : '/membership_basic_details',
    GROUP : '/membership_group_details',
    INSTITUTION : '/mem_institutions',
    SAVING_JOINT_ACCOUNT_HOLDER_DETAILS : '/sb_joint_acc_holder_details',
    GET_SB_ACCOUNT_HOLDER_DETAILS_BY_SB_ID: '/get_joint_holder_details_by_sb_id',
    SB_COMMUNICATION_DETAILS : '/sb_communications',
    SB_COMMUNICATION_BY_ACCOUNT_ID : '/get_by_sb_acc_id_or_joint_holder_id',
    SB_KYC_DETAILS : '/sb_acc_kyc_details',
    KYC_DOC_TYPE: '/kyc_document_types',
    SB_SERVICE_TYPES : '/service_types',
    SB_KYC_DETAILS_BY_SB_ID:'/get_kyc_details_by_sb_acc_id',
    SB_ACC_NOMINEE_DETAILS: '/sb_nominee',
    SB_NOMINEE_DETAILS_BY_SB_ACC_ID : '/get_nominee_details_by_sb_account_id',
    SB_SERVICES_CHARGES : '/sb_account_services_opted',
    SB_SERVICES_BY_SB_ID : '/get_account_services_by_sb_acc_id',
    ACTIVE_PRODUCT_BYPRODUCT_ID:'/get_active_product_based_on_product_id',
    PRODUCTS_WITH_CURRENT_DATE:"/get_all_active_product_based_on_pacs_id",
    INTEREST_POSTING_FREQUENCYS:'/interest_posting_frequency',
    SB_ACC_GUARDAIN_DETAILS: '/sb_guardian_details',
    SB_ACC_GUARDIAN_GET_BY_ACCOUNT_NUMBER:'/get_guardian_details_by_account_number',
    SB_ACC_DETAILS_BY_ADMISSION_NUMBER_AND_ID : '/get_saving_account_by_admission_number_and_id',
    SB_ACCOUNT_ADMISSION_NUMBER : '/get_saving_account_by_admission_number',
    SB_GROUP_PROMOTER_DETAILS : '/group_promoters',
    SB_INSTITUTION_PROMOTER_DETAILS : '/institution_promoter_details',
    MEMBER_BY_ADMISSIONUMBER : '/get_by_admission_number',
    GET_COMMON_STATUS_BY_CATEGORY_ID:'/get_common_status_by_category_id',
    GET_WORKFLOW_ID:'/get_workflow_id',
    GET_COMMUNICATION_DETAILS_BY_ID_MEMBER_TYPE_ADMISSION_NUMBER : '/get_communcation_by_accountId_and_member_type_and_admission_number',
    GET_COMMUNICATION_DETAILS_BY_MEMBER_TYPE_ADMISSION_NUMBER : '/get_communcation_by_member_type_and_admission_number',   
    GET_COMMUNICATE_BY_ADMISSION_NUMBER:'/get_all_communications_by_admission_number',
    GET_SB_NOMINEE_BY_ACCOUNT_NUMBER : "/get_nominee_details_by_account_number", 

    //loan config
    CHARGES_TYPES:'/charges_types',
    COLLATERAL_TYPES:'/collateral_types',
    COLLECTION_COMPONENT:'/collection_components',
    CROP_TYPES:'/crop',
    INTEREST_CALCULATION_TYPES:'/interest_calculation_types',
    INTEREST_POSTING_FREQUENCY:'/interest_posting_frequencies',
    LOAN_ACCOUNT_TYPE:'/loan_account_types',
    LOAN_PURPOSE:'/loan_purposes',
    REPAYMENT_FREQUENCY:'/repayment_frequency',
    SCALE_OF_FINANCE_CONFIGS:'/scale_of_finance_configs',
    FARMER_CATEGORY:'/farmer_category',
    INSURENCE_VENDOR_DETAILS:'/insurance_vendor_details',
    FINANCIAR_BANK_DETAILS:'/financiar_bank_details',

    //member config
    ACTIVITY:'/activitiy',
    ACTIVITY_GL_HEADS_MAPPING:'/activity_gl_heads_mapping',
    ASSET_TYPES:'/asset_types',
    COVERED_VILLAGES:'/covered_villages',
    GET_ALL_COVERED_VILLAGES_BY_PAC_ID:'/get_all_covered_villages_By_pac_id',
    FEE_TYPE:'/fee_type',
    GL_HEADS:'/gl_heads',
    GROUP_TYPES:'/group_types',
    INCORPORATION_TYPES:'/in_corporation_types',
    IRRIGATION_TYPE:'/irrigation_type',
    MCR_DETAILS:'/mcr_details',
    MEMBER_TYPES:'/member_types',
    OPERATION_TYPES:'/operation_types',
    SEASON_TYPES:'/season_types',
    SETTINGS:'/settings',
    SOIL_TYPES:'/soil_types',
    UOM:'/land_uom',
    UOM_CALCULATION:'/land_uom_calculation',
    SUB_CATEGORY:'/get_sub_category',
    WORK_FLOWSTEPS:'/work_flow_steps',
    GET_WORK_FLOW_STEPS:'/get_workflow_id',
    WORK_FLOW_STEPS_LIST:'/get_all_workflow_steps',
    // COMMON_STATUS_BY_CATEGORY:'/get_status_by_category',
    WORK_FLOW_STEPS_BY_CATEGORY_AND_WORKFLOW:'/get_work_flow_steps_by_category_and_workflow',
    // ORG_HEIRARCHY:'/org_heirarchy',
    // COMMON_STATUS:'/common_status',
    KYC_DOCUMENT_TYPES:'/kyc_doc_types',
    WATER_SOURCE_TYPES:'/water_source_type',
    ORG_HEIRACHY:'/org_heirarchy',
    SUB_PRODUCTS:'/sub_products',
  
    //cash config
    DENOMINATION:'/denomintaion',
    VAULT_CASH :'/vault_cash',

    //agent details config
    DEVICE_CONFIG:'/device_config',
    AGENT_COMMISSION_POLICY:'/agent_commission_policy',
    AGENT_SECURITY_CONFIG:'/agent_security_config',
    GENDER: '/gender',

    //investments config
    INVESTMENTS_KYC_DOC_TYPES:'/kyc_doc_types',
    INVESTED_BANK_DETAILS:'/invested_bank_details',
    UPDATE_INVESTED_BANK_DETAILS_STATUS:'/update_invested_bank_details_status',
    INVESTMENT_WORK_FLOW:'/work_flow',
    MEMBER_KYC_BY_ADMISSION_NUMBER : "/get_all_membership_kyc_details_by_admission_number",
    MEMBERSHIP_KYC_DETAILS: '/membership_kyc_details',


    //lockers
    LOCKER_VENDOR_DETAILS:'/locker_vendor_details',
    LOCKER_CONFIGS:'/locker_configs',

    //common master
    USERL_ROLES : "/user_roles",

    
    INDIVIDUAL_MEMBER_DETAILS :'/individual_member_details',
    SI_LOAN_COMMUNICATION_DETAILS : '/si_loan_communication',
    SI_LOAN_COMMUNICATION_BY_ACCOUNT_ID : '/get_communications_by_loan_application_id',
    GET_APPROVED_RD_PRODUCT_DEFINITION:'/get_approved_rd_product_definition',
    GET_BY_RD_PRODUCT_ID:'/get_by_rd_product_id',
    GET_INTEREST_POLICY_BY_PRODUCT_ID:'/get_interst_policy_config_by_product_id',
    GET_RD_MATURITY_AMOUNT_ON_CLOSER:'/get_rd_maturity_amount_on_closure',
    GET_ALL_CAST_AND_SUB_CASTE:'/get_all_caste_and_sub_castes',
    GET_ALL_QUALIFICATION_AND_SUB_QUALIFICATION:'/get_all_qualification_and_sub_qualification',
    GET_ALL_ASSET_AND_SUB_ASSET_TYPES:'/get_all_asset_and_sub_asset_types'

    
}