
export const LoanConfigConstants = {
    APPORTION_TYPES: "/menu/configurations/loan_config/apportion_types",
    ADD_APPORTION_TYPE: "/menu/configurations/loan_config/add_apportion_type",
    CHARGES_TYPES: "/menu/configurations/loan_config/charges_types",
    ADD_CHARGES_TYPE: "/menu/configurations/loan_config/add_charges_type",
    COLLATERAL_TYPES: "/menu/configurations/loan_config/collateral_types",
    ADD_COLLATERAL_TYPE: "/menu/configurations/loan_config/add_collateral_type",
    COMMON_CATEGORY: "/menu/configurations/loan_config/common_category",
    ADD_COMMON_CATEGORY: "/menu/configurations/loan_config/add_common_category",
    CROP_TYPES: "/menu/configurations/loan_config/crop_types",
    ADD_CROP_TYPE: "/menu/configurations/loan_config/add_crop_type",
    LOAN_ACCOUNT_TYPES: "/menu/configurations/loan_config/account_types",
    ADD_LOAN_ACCOUNT_TYPE: "/menu/configurations/loan_config/add_account_type",
    LOAN_PURPOSE: "/menu/configurations/loan_config/purpose",
    ADD_LOAN_PURPOSE: "/menu/configurations/loan_config/add_purpose",
    REPAYMENT_MODE: "/menu/configurations/loan_config/repayment_mode",
    ADD_REPAYMENT_MODE: "/menu/configurations/loan_config/add_repayment_mode",
    SCALE_OF_FINANCE_CONFIG: "/menu/configurations/loan_config/scale_of_finance_config",
    ADD_SCALE_OF_FINANCE_CONFIG: "/menu/configurations/loan_config/add_scale_of_finance_config",
    WORK_FLOW: "/menu/configurations/loan_config/workflow",
    ADD_WORK_FLOW: "/menu/configurations/loan_config/add_workflow",
    FARMER_TYPES: "/menu/configurations/loan_config/farmer_types",
    ADD_FARMER_TYPE: "/menu/configurations/loan_config/add_farmer_type",
    INSURER_DETAILS: "/menu/configurations/loan_config/insurer_details",
    ADD_INSURER_DETAILS: "/menu/configurations/loan_config/add_insurer_details",
    DOCUMENT_TYPES: "/menu/configurations/loan_config/document_types",
    ADD_DOCUMENT_TYPE: "/menu/configurations/loan_config/add_document_type",
    SERVICE_TYPES: "/menu/configurations/loan_config/service_types",
    ADD_SERVICE_TYPE: "/menu/configurations/loan_config/add_service_type",
}
